# addresses.feature - AUTO-GENERATED by karate-generator.py (Python + Groq FREE)
# Generated: 2026-05-22T08:59:34.282950
# Feature: Addresses
# API: https://ecommerce.routemisr.com/api/v1
# Uses REAL API discovery - status codes verified against live API

Feature: RetailShop Addresses API
  Background:
    * url 'https://ecommerce.routemisr.com/api/v1'
    * def testEmail = 'qelead.test2026@gmail.com'
    * def testPassword = 'QeTest@2026'
    Given path '/auth/signin'
    And request { "email": "#(testEmail)", "password": "#(testPassword)" }
    When method POST
    Then status 200
    * def authToken = response.token
    * def userId = response.user._id

  Scenario: Happy Path - Get logged in user addresses
    Given path '/addresses'
    And header token = authToken
    When method GET
    Then status 200

  Scenario: No Auth Token - Get logged in user addresses
    Given path '/addresses'
    When method GET
    Then status 401
    And match response == { error: "You are not logged in. Please login to get access" }

  Scenario: Invalid Auth Token - Get logged in user addresses
    Given path '/addresses'
    And header token = 'invalid-token-xyz'
    When method GET
    Then status 401
    And match response == { error: "You are not logged in. Please login to get access" }

  Scenario: Happy Path - Add new address
    Given path '/addresses'
    And header token = authToken
    And request { details: 'test details', phone: '1234567890', city: 'test city' }
    When method POST
    Then status 200

  Scenario: No Auth Token - Add new address
    Given path '/addresses'
    And request { details: 'test details', phone: '1234567890', city: 'test city' }
    When method POST
    Then status 401
    And match response == { error: "You are not logged in. Please login to get access" }

  Scenario: Invalid Auth Token - Add new address
    Given path '/addresses'
    And header token = 'invalid-token-xyz'
    And request { details: 'test details', phone: '1234567890', city: 'test city' }
    When method POST
    Then status 401
    And match response == { error: "You are not logged in. Please login to get access" }

  Scenario: Missing Required Fields - Add new address (details)
    Given path '/addresses'
    And header token = authToken
    And request { phone: '1234567890', city: 'test city' }
    When method POST
    Then status 400

  Scenario: Missing Required Fields - Add new address (phone)
    Given path '/addresses'
    And header token = authToken
    And request { details: 'test details', city: 'test city' }
    When method POST
    Then status 400

  Scenario: Missing Required Fields - Add new address (city)
    Given path '/addresses'
    And header token = authToken
    And request { details: 'test details', phone: '1234567890' }
    When method POST
    Then status 400

  Scenario: Happy Path - Remove address
    Given path '/addresses/6428ebc6dc1175abc65ca0b9'
    And header token = authToken
    When method DELETE
    Then status 200

  Scenario: No Auth Token - Remove address
    Given path '/addresses/6428ebc6dc1175abc65ca0b9'
    When method DELETE
    Then status 401
    And match response == { error: "You are not logged in. Please login to get access" }

  Scenario: Invalid Auth Token - Remove address
    Given path '/addresses/6428ebc6dc1175abc65ca0b9'
    And header token = 'invalid-token-xyz'
    When method DELETE
    Then status 401
    And match response == { error: "You are not logged in. Please login to get access" }

  Scenario: Not Found - Remove address
    Given path '/addresses/000000000000000000000000'
    And header token = authToken
    When method DELETE
    Then status 404