# addresses.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T03:39:11.934Z
# Feature: Addresses
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Addresses API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'

Scenario: Get all addresses - happy path with authenticated user
  # Test: GET /addresses returns 200 with user's addresses
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  Given path '/addresses'
  And header token = authToken
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Add new address - happy path with valid required fields
  # Test: POST /addresses with details, phone, city returns 200
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  Given path '/addresses'
  And header token = authToken
  And request { "details": "123 Main Street Apt 4", "phone": "01001234567", "city": "Cairo" }
  When method POST
  Then status 200
  And match response.data._id == '#string'

Scenario: Delete address - happy path with valid address ID
  # Test: DELETE /addresses/{addressId} returns 200 for existing address
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  Given path '/addresses'
  And header token = authToken
  And request { "details": "456 Oak Avenue", "phone": "01009876543", "city": "Alexandria" }
  When method POST
  Then status 200
  * def addressId = response.data._id
  
  Given path '/addresses/' + addressId
  And header token = authToken
  When method DELETE
  Then status 200

Scenario: Get addresses without auth token - expect 401
  # Test: GET /addresses without token header returns 401
  Given path '/addresses'
  When method GET
  Then status 401

Scenario: Add address without auth token - expect 401
  # Test: POST /addresses without token header returns 401
  Given path '/addresses'
  And request { "details": "789 Pine Road", "phone": "01112345678", "city": "Giza" }
  When method POST
  Then status 401

Scenario: Delete address without auth token - expect 401
  # Test: DELETE /addresses/{addressId} without token header returns 401
  Given path '/addresses/507f1f77bcf86cd799439011'
  When method DELETE
  Then status 401

Scenario: Get addresses with invalid auth token - expect 401
  # Test: GET /addresses with invalid token returns 401
  Given path '/addresses'
  And header token = 'invalid-token-xyz'
  When method GET
  Then status 401

Scenario: Add address with invalid auth token - expect 401
  # Test: POST /addresses with invalid token returns 401
  Given path '/addresses'
  And header token = 'invalid-token-xyz'
  And request { "details": "321 Elm Street", "phone": "01223334444", "city": "Helwan" }
  When method POST
  Then status 401

Scenario: Delete address with invalid auth token - expect 401
  # Test: DELETE /addresses/{addressId} with invalid token returns 401
  Given path '/addresses/507f1f77bcf86cd799439011'
  And header token = 'invalid-token-xyz'
  When method DELETE
  Then status 401

Scenario: Add address missing details field - expect 400
  # Test: POST /addresses without details returns 400
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  Given path '/addresses'
  And header token = authToken
  And request { "phone": "01334445555", "city": "Zagazig" }
  When method POST
  Then status 400

Scenario: Add address missing phone field - expect 400
  # Test: POST /addresses without phone returns 400
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  Given path '/addresses'
  And header token = authToken
  And request { "details": "654 Maple Drive", "city": "Ismailia" }
  When method POST
  Then status 400

Scenario: Add address missing city field - expect 400
  # Test: POST /addresses without city returns 400
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  Given path '/addresses'
  And header token = authToken
  And request { "details": "987 Birch Lane", "phone": "01445556666" }
  When method POST
  Then status 400

Scenario: Delete non-existent address - expect 404
  # Test: DELETE /addresses/{addressId} with non-existent ID returns 404
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  Given path '/addresses/000000000000000000000000'
  And header token = authToken
  When method DELETE
  Then status 404