# addresses.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T02:56:54.696Z
# Feature: Addresses
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Addresses API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'
  * def nonExistentAddressId = '000000000000000000000000'
  * def invalidAddressId = 'invalid-id'

Scenario: Login to get auth token for all address tests
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  * def userId = response.user._id

# ============================================
# GET /addresses - Retrieve user addresses
# ============================================

Scenario: Get addresses - Happy path with valid token
  # Setup: Login to get token
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  # Test: Get addresses with valid token
  Given path '/addresses'
  And header token = authToken
  When method GET
  Then status 200
  And match response != null
  And match response.data == '#[]'

Scenario: Get addresses - Unauthorized without token
  # Test: Get addresses without token header - should return 401
  Given path '/addresses'
  When method GET
  Then status 401

Scenario: Get addresses - Unauthorized with invalid token
  # Test: Get addresses with invalid token - should return 401
  Given path '/addresses'
  And header token = 'invalid-token-xyz'
  When method GET
  Then status 401

# ============================================
# POST /addresses - Add new address
# ============================================

Scenario: Add address - Happy path with all required fields
  # Setup: Login to get token
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  # Test: Add new address with all required fields
  Given path '/addresses'
  And header token = authToken
  And request { "details": "123 Main Street Apartment 4B", "phone": "201012345678", "city": "Cairo" }
  When method POST
  Then status 200
  And match response.data != null
  * def createdAddressId = response.data._id

Scenario: Add address - Unauthorized without token
  # Test: Add address without token - should return 401
  Given path '/addresses'
  And request { "details": "123 Main Street", "phone": "201012345678", "city": "Cairo" }
  When method POST
  Then status 401

Scenario: Add address - Unauthorized with invalid token
  # Test: Add address with invalid token - should return 401
  Given path '/addresses'
  And header token = 'invalid-token-xyz'
  And request { "details": "123 Main Street", "phone": "201012345678", "city": "Cairo" }
  When method POST
  Then status 401

Scenario: Add address - Missing required field: details
  # Setup: Login to get token
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  # Test: Add address without details field - should return 400
  Given path '/addresses'
  And header token = authToken
  And request { "phone": "201012345678", "city": "Cairo" }
  When method POST
  Then status 400

Scenario: Add address - Missing required field: phone
  # Setup: Login to get token
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  # Test: Add address without phone field - should return 400
  Given path '/addresses'
  And header token = authToken
  And request { "details": "123 Main Street", "city": "Cairo" }
  When method POST
  Then status 400

Scenario: Add address - Missing required field: city
  # Setup: Login to get token
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  # Test: Add address without city field - should return 400
  Given path '/addresses'
  And header token = authToken
  And request { "details": "123 Main Street", "phone": "201012345678" }
  When method POST
  Then status 400

Scenario: Add address - Invalid phone data type (number instead of string)
  # Setup: Login to get token
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  # Test: Add address with phone as number - should return 400
  Given path '/addresses'
  And header token = authToken
  And request { "details": "123 Main Street", "phone": 201012345678, "city": "Cairo" }
  When method POST
  Then status 400

Scenario: Add address - Invalid details data type (number instead of string)
  # Setup: Login to get token
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  # Test: Add address with details as number - should return 400
  Given path '/addresses'
  And header token = authToken
  And request { "details": 12345, "phone": "201012345678", "city": "Cairo" }
  When method POST
  Then status 400

Scenario: Add address - Invalid city data type (number instead of string)
  # Setup: Login to get token
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  # Test: Add address with city as number - should return 400
  Given path '/addresses'
  And header token = authToken
  And request { "details": "123 Main Street", "phone": "201012345678", "city": 12345 }
  When method POST
  Then status 400

# ============================================
# DELETE /addresses/{addressId} - Remove address
# ============================================

Scenario: Delete address - Happy path with valid addressId
  # Setup: Login to get token
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  # Setup: Create an address to delete
  Given path '/addresses'
  And header token = authToken
  And request { "details": "Temporary Address For Deletion", "phone": "201087654321", "city": "Giza" }
  When method POST
  Then status 200
  * def addressIdToDelete = response.data._id
  
  # Test: Delete the created address
  Given path '/addresses/' + addressIdToDelete
  And header token = authToken
  When method DELETE
  Then status 200

Scenario: Delete address - Unauthorized without token
  # Test: Delete address without token - should return 401
  Given path '/addresses/' + nonExistentAddressId
  When method DELETE
  Then status 401

Scenario: Delete address - Unauthorized with invalid token
  # Test: Delete address with invalid token - should return 401
  Given path '/addresses/' + nonExistentAddressId
  And header token = 'invalid-token-xyz'
  When method DELETE
  Then status 401

Scenario: Delete address - Not found with non-existent valid MongoDB ID
  # Setup: Login to get token
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  # Test: Delete address with non-existent MongoDB ID - should return 404
  Given path '/addresses/' + nonExistentAddressId
  And header token = authToken
  When method DELETE
  Then status 404

Scenario: Delete address - Invalid address ID format
  # Setup: Login to get token
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  
  # Test: Delete address with invalid MongoDB ID format - should return 500
  Given path '/addresses/' + invalidAddressId
  And header token = authToken
  When method DELETE
  Then status 500