# authentication.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T02:55:50.365Z
# Feature: Authentication
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Authentication API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'

Scenario: SignUp - Happy path with valid credentials
  # Test that a new user can register successfully with all required fields
  Given path '/auth/signup'
  And request { "name": "Test User", "email": "testuser" + java.lang.System.currentTimeMillis() + "@gmail.com", "password": "ValidPass@123", "rePassword": "ValidPass@123", "phone": "+201234567890" }
  When method POST
  Then status 201
  And match response.message == "User registered successfully"
  And match response.data.name != null
  And match response.data._id != null

Scenario: SignUp - Email already exists returns 409
  # Test that registering with an existing email returns conflict error
  Given path '/auth/signup'
  And request { "name": "Existing User", "email": "#(testEmail)", "password": "ValidPass@123", "rePassword": "ValidPass@123", "phone": "+201234567890" }
  When method POST
  Then status 409
  And match response.message contains "Email already"

Scenario: SignUp - Missing name field returns 400
  # Test that missing required name field returns validation error
  Given path '/auth/signup'
  And request { "email": "newuser" + java.lang.System.currentTimeMillis() + "@gmail.com", "password": "ValidPass@123", "rePassword": "ValidPass@123", "phone": "+201234567890" }
  When method POST
  Then status 400
  And match response.message contains "name"

Scenario: SignUp - Missing email field returns 400
  # Test that missing required email field returns validation error
  Given path '/auth/signup'
  And request { "name": "Test User", "password": "ValidPass@123", "rePassword": "ValidPass@123", "phone": "+201234567890" }
  When method POST
  Then status 400
  And match response.message contains "email"

Scenario: SignUp - Missing password field returns 400
  # Test that missing required password field returns validation error
  Given path '/auth/signup'
  And request { "name": "Test User", "email": "newuser" + java.lang.System.currentTimeMillis() + "@gmail.com", "rePassword": "ValidPass@123", "phone": "+201234567890" }
  When method POST
  Then status 400
  And match response.message contains "password"

Scenario: SignUp - Missing rePassword field returns 400
  # Test that missing required rePassword field returns validation error
  Given path '/auth/signup'
  And request { "name": "Test User", "email": "newuser" + java.lang.System.currentTimeMillis() + "@gmail.com", "password": "ValidPass@123", "phone": "+201234567890" }
  When method POST
  Then status 400
  And match response.message contains "rePassword"

Scenario: SignUp - Missing phone field returns 400
  # Test that missing required phone field returns validation error
  Given path '/auth/signup'
  And request { "name": "Test User", "email": "newuser" + java.lang.System.currentTimeMillis() + "@gmail.com", "password": "ValidPass@123", "rePassword": "ValidPass@123" }
  When method POST
  Then status 400
  And match response.message contains "phone"

Scenario: SignUp - Password and rePassword mismatch returns 400
  # Test that mismatched passwords return validation error
  Given path '/auth/signup'
  And request { "name": "Test User", "email": "newuser" + java.lang.System.currentTimeMillis() + "@gmail.com", "password": "ValidPass@123", "rePassword": "DifferentPass@123", "phone": "+201234567890" }
  When method POST
  Then status 400
  And match response.message contains "password"

Scenario: SignUp - Invalid email format returns 400
  # Test that invalid email format returns validation error
  Given path '/auth/signup'
  And request { "name": "Test User", "email": "invalidemail", "password": "ValidPass@123", "rePassword": "ValidPass@123", "phone": "+201234567890" }
  When method POST
  Then status 400
  And match response.message contains "email"

Scenario: SignUp - Invalid phone format returns 400
  # Test that invalid phone format returns validation error
  Given path '/auth/signup'
  And request { "name": "Test User", "email": "newuser" + java.lang.System.currentTimeMillis() + "@gmail.com", "password": "ValidPass@123", "rePassword": "ValidPass@123", "phone": "invalid" }
  When method POST
  Then status 400
  And match response.message contains "phone"

Scenario: SignUp - Name with wrong data type returns 400
  # Test that sending number instead of string for name returns validation error
  Given path '/auth/signup'
  And request { "name": 12345, "email": "newuser" + java.lang.System.currentTimeMillis() + "@gmail.com", "password": "ValidPass@123", "rePassword": "ValidPass@123", "phone": "+201234567890" }
  When method POST
  Then status 400
  And match response.message contains "name"

Scenario: SignUp - Email with wrong data type returns 400
  # Test that sending number instead of string for email returns validation error
  Given path '/auth/signup'
  And request { "name": "Test User", "email": 12345, "password": "ValidPass@123", "rePassword": "ValidPass@123", "phone": "+201234567890" }
  When method POST
  Then status 400
  And match response.message contains "email"

Scenario: SignUp - Password with wrong data type returns 400
  # Test that sending number instead of string for password returns validation error
  Given path '/auth/signup'
  And request { "name": "Test User", "email": "newuser" + java.lang.System.currentTimeMillis() + "@gmail.com", "password": 12345, "rePassword": "ValidPass@123", "phone": "+201234567890" }
  When method POST
  Then status 400
  And match response.message contains "password"

Scenario: SignUp - Phone with wrong data type returns 400
  # Test that sending number instead of string for phone returns validation error
  Given path '/auth/signup'
  And request { "name": "Test User", "email": "newuser" + java.lang.System.currentTimeMillis() + "@gmail.com", "password": "ValidPass@123", "rePassword": "ValidPass@123", "phone": 12345 }
  When method POST
  Then status 400
  And match response.message contains "phone"

Scenario: SignIn - Happy path with valid credentials
  # Test that user can login successfully with valid email and password
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  And match response.token != null
  And match response.user._id != null
  And match response.user.email == testEmail

Scenario: SignIn - Incorrect password returns 401
  # Test that login with wrong password returns authentication error
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "WrongPassword123" }
  When method POST
  Then status 401
  And match response.message contains "Incorrect"

Scenario: SignIn - Non-existent email returns 401
  # Test that login with non-existent email returns authentication error
  Given path '/auth/signin'
  And request { "email": "nonexistent@gmail.com", "password": "#(testPassword)" }
  When method POST
  Then status 401
  And match response.message contains "No user"

Scenario: SignIn - Missing email field returns 400
  # Test that missing required email field returns validation error
  Given path '/auth/signin'
  And request { "password": "#(testPassword)" }
  When method POST
  Then status 400
  And match response.message contains "email"

Scenario: SignIn - Missing password field returns 400
  # Test that missing required password field returns validation error
  Given path '/auth/signin'
  And request { "email": "#(testEmail)" }
  When method POST
  Then status 400
  And match response.message contains "password"

Scenario: SignIn - Email with wrong data type returns 400
  # Test that sending number instead of string for email returns validation error
  Given path '/auth/signin'
  And request { "email": 12345, "password": "#(testPassword)" }
  When method POST
  Then status 400
  And match response.message contains "email"

Scenario: SignIn - Password with wrong data type returns 400
  # Test that sending number instead of string for password returns validation error
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": 12345 }
  When method POST
  Then status 400
  And match response.message contains "password"

Scenario: SignIn - Invalid email format returns 400
  # Test that invalid email format returns validation error
  Given path '/auth/signin'
  And request { "email": "invalidemail", "password": "#(testPassword)" }
  When method POST
  Then status 400
  And match response.message contains "email"

Scenario: ForgotPassword - Happy path with valid email
  # Test that password reset email is sent successfully for existing user
  Given path '/auth/forgotPasswords'
  And request { "email": "#(testEmail)" }
  When method POST
  Then status 200
  And match response.message contains "email"

Scenario: ForgotPassword - Non-existent email returns 404
  # Test that requesting password reset for non-existent email returns not found error
  Given path '/auth/forgotPasswords'
  And request { "email": "nonexistent@gmail.com" }
  When method POST
  Then status 404
  And match response.message contains "No user"

Scenario: ForgotPassword - Missing email field returns 400
  # Test that missing required email field returns validation error
  Given path '/auth/forgotPasswords'
  And request { }
  When method POST
  Then status 400
  And match response.message contains "email"

Scenario: ForgotPassword - Email with wrong data type returns 400
  # Test that sending number instead of string for email returns validation error
  Given path '/auth/forgotPasswords'
  And request { "email": 12345 }
  When method POST
  Then status 400
  And match response.message contains "email"

Scenario: ForgotPassword - Invalid email format returns 400
  # Test that invalid email format returns validation error
  Given path '/auth/forgotPasswords'
  And request { "email": "invalidemail" }
  When method POST
  Then status 400
  And match response.message contains "email"