# authentication.feature - AUTO-GENERATED by karate-generator.py (Python + Groq FREE)
# Generated: 2026-05-22T08:58:32.911264
# Feature: Authentication
# API: https://ecommerce.routemisr.com/api/v1
# Uses REAL API discovery - status codes verified against live API

Feature: RetailShop Authentication API
  Background:
    * url 'https://ecommerce.routemisr.com/api/v1'
    * def testEmail = 'qelead.test2026@gmail.com'
    * def testPassword = 'QeTest@2026'
    Given path '/auth/signin'
    And request { "email": "#(testEmail)", "password": "#(testPassword)" }
    When method POST
    Then status 200
    * def authToken = response.token
    * def userId = response.user._id

  Scenario: Happy path - Register a new user account
    Given path '/auth/signup'
    And request { "name": "Test User", "email": "test@example.com", "password": "Test@123", "rePassword": "Test@123", "phone": "1234567890" }
    When method POST
    Then status 201

  Scenario: Happy path - Login and get JWT token
    Given path '/auth/signin'
    And request { "email": "#(testEmail)", "password": "#(testPassword)" }
    When method POST
    Then status 200

  Scenario: Happy path - Send password reset email
    Given path '/auth/forgotPasswords'
    And request { "email": "#(testEmail)" }
    When method POST
    Then status 200

  Scenario: No auth token - Login and get JWT token
    Given path '/auth/signin'
    And request { "email": "#(testEmail)", "password": "#(testPassword)" }
    When method POST
    Then status 200
    * def authToken = response.token
    Given path '/auth/signin'
    And request { "email": "#(testEmail)", "password": "#(testPassword)" }
    When method POST
    Then status 200

  Scenario: Invalid auth token - Register a new user account
    Given path '/auth/signup'
    And header token = 'invalid-token-xyz'
    And request { "name": "Test User", "email": "test@example.com", "password": "Test@123", "rePassword": "Test@123", "phone": "1234567890" }
    When method POST
    Then status 401

  Scenario: Missing required fields - Register a new user account (name)
    Given path '/auth/signup'
    And request { "email": "test@example.com", "password": "Test@123", "rePassword": "Test@123", "phone": "1234567890" }
    When method POST
    Then status 400

  Scenario: Missing required fields - Register a new user account (email)
    Given path '/auth/signup'
    And request { "name": "Test User", "password": "Test@123", "rePassword": "Test@123", "phone": "1234567890" }
    When method POST
    Then status 400

  Scenario: Missing required fields - Register a new user account (password)
    Given path '/auth/signup'
    And request { "name": "Test User", "email": "test@example.com", "rePassword": "Test@123", "phone": "1234567890" }
    When method POST
    Then status 400

  Scenario: Missing required fields - Register a new user account (rePassword)
    Given path '/auth/signup'
    And request { "name": "Test User", "email": "test@example.com", "password": "Test@123", "phone": "1234567890" }
    When method POST
    Then status 400

  Scenario: Missing required fields - Register a new user account (phone)
    Given path '/auth/signup'
    And request { "name": "Test User", "email": "test@example.com", "password": "Test@123", "rePassword": "Test@123" }
    When method POST
    Then status 400

  Scenario: Missing required fields - Login and get JWT token (email)
    Given path '/auth/signin'
    And request { "password": "#(testPassword)" }
    When method POST
    Then status 400

  Scenario: Missing required fields - Login and get JWT token (password)
    Given path '/auth/signin'
    And request { "email": "#(testEmail)" }
    When method POST
    Then status 400

  Scenario: Missing required fields - Send password reset email (email)
    Given path '/auth/forgotPasswords'
    And request {}
    When method POST
    Then status 400

  Scenario: Not found - Send password reset email
    Given path '/auth/forgotPasswords'
    And request { "email": "000000000000000000000000" }
    When method POST
    Then status 404