# authentication.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T03:38:24.999Z
# Feature: Authentication
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Authentication API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'

Scenario: POST /auth/signup - Happy Path - Register new user successfully
  # Tests successful user registration with all required fields
  Given path '/auth/signup'
  And request
    """
    {
      "name": "Test User " + java.lang.System.currentTimeMillis(),
      "email": "testuser" + java.lang.System.currentTimeMillis() + "@example.com",
      "password": "TestPass@123",
      "rePassword": "TestPass@123",
      "phone": "01012345678"
    }
    """
  When method POST
  Then status 201
  And match response.message == '#notnull'
  And match response.user._id == '#notnull'

Scenario: POST /auth/signup - Missing required field: name - Expect 400
  # Tests signup fails when name field is omitted
  Given path '/auth/signup'
  And request
    """
    {
      "email": "testuser" + java.lang.System.currentTimeMillis() + "@example.com",
      "password": "TestPass@123",
      "rePassword": "TestPass@123",
      "phone": "01012345678"
    }
    """
  When method POST
  Then status 400

Scenario: POST /auth/signup - Missing required field: email - Expect 400
  # Tests signup fails when email field is omitted
  Given path '/auth/signup'
  And request
    """
    {
      "name": "Test User",
      "password": "TestPass@123",
      "rePassword": "TestPass@123",
      "phone": "01012345678"
    }
    """
  When method POST
  Then status 400

Scenario: POST /auth/signup - Missing required field: password - Expect 400
  # Tests signup fails when password field is omitted
  Given path '/auth/signup'
  And request
    """
    {
      "name": "Test User",
      "email": "testuser" + java.lang.System.currentTimeMillis() + "@example.com",
      "rePassword": "TestPass@123",
      "phone": "01012345678"
    }
    """
  When method POST
  Then status 400

Scenario: POST /auth/signup - Missing required field: rePassword - Expect 400
  # Tests signup fails when rePassword field is omitted
  Given path '/auth/signup'
  And request
    """
    {
      "name": "Test User",
      "email": "testuser" + java.lang.System.currentTimeMillis() + "@example.com",
      "password": "TestPass@123",
      "phone": "01012345678"
    }
    """
  When method POST
  Then status 400

Scenario: POST /auth/signup - Missing required field: phone - Expect 400
  # Tests signup fails when phone field is omitted
  Given path '/auth/signup'
  And request
    """
    {
      "name": "Test User",
      "email": "testuser" + java.lang.System.currentTimeMillis() + "@example.com",
      "password": "TestPass@123",
      "rePassword": "TestPass@123"
    }
    """
  When method POST
  Then status 400

Scenario: POST /auth/signin - Happy Path - Login successfully and receive JWT token
  # Tests successful login with valid credentials
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  And match response.token == '#notnull'
  And match response.user._id == '#notnull'
  And match response.user.email == testEmail

Scenario: POST /auth/signin - Missing required field: email - Expect 400
  # Tests signin fails when email field is omitted
  Given path '/auth/signin'
  And request { "password": "#(testPassword)" }
  When method POST
  Then status 400

Scenario: POST /auth/signin - Missing required field: password - Expect 400
  # Tests signin fails when password field is omitted
  Given path '/auth/signin'
  And request { "email": "#(testEmail)" }
  When method POST
  Then status 400

Scenario: POST /auth/signin - Incorrect email or password - Expect 401
  # Tests signin fails with invalid credentials
  Given path '/auth/signin'
  And request { "email": "invalid@example.com", "password": "WrongPassword123" }
  When method POST
  Then status 401

Scenario: POST /auth/forgotPasswords - Happy Path - Send password reset email successfully
  # Tests successful password reset email sent for existing user
  Given path '/auth/forgotPasswords'
  And request { "email": "#(testEmail)" }
  When method POST
  Then status 200
  And match response.message == '#notnull'

Scenario: POST /auth/forgotPasswords - Missing required field: email - Expect 400
  # Tests forgot password fails when email field is omitted
  Given path '/auth/forgotPasswords'
  And request {}
  When method POST
  Then status 400

Scenario: POST /auth/forgotPasswords - User not found with email - Expect 404
  # Tests forgot password fails when email does not exist in database
  Given path '/auth/forgotPasswords'
  And request { "email": "nonexistent" + java.lang.System.currentTimeMillis() + "@example.com" }
  When method POST
  Then status 404