# brands.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T02:56:17.062Z
# Feature: Brands
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Brands API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'

Scenario: Get all brands - Happy path returns 200 with brands list
  Given path '/brands'
  When method GET
  Then status 200
  And match response.data == '#[]'
  And match response.results > 0

Scenario: Get all brands - Verify response structure contains brand objects
  Given path '/brands'
  When method GET
  Then status 200
  And match response.data[0] contains { _id: '#string', name: '#string', slug: '#string', image: '#string' }

Scenario: Get all brands - Verify brand object has required fields
  Given path '/brands'
  When method GET
  Then status 200
  And match response.data[0]._id == '#regex [a-f0-9]{24}'
  And match response.data[0].name == '#string'
  And match response.data[0].slug == '#string'

Scenario: Get brand by ID - Happy path with valid brand ID returns 200
  # First fetch a real brand ID
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0]._id
  # Now test get by ID
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data._id == brandId
  And match response.data.name == '#string'

Scenario: Get brand by ID - Non-existent brand ID returns 404
  Given path '/brands/000000000000000000000000'
  When method GET
  Then status 404

Scenario: Get brand by ID - Invalid ObjectId format returns 500
  Given path '/brands/invalid-id-format'
  When method GET
  Then status 500

Scenario: Get brand by ID - Verify response contains complete brand object
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0]._id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data contains { _id: '#string', name: '#string', slug: '#string', image: '#string' }
  And match response.data._id == '#regex [a-f0-9]{24}'

Scenario: Get brand by ID - Verify single brand response is not array
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0]._id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data == '#object'
  And match response.data != '#[]'

Scenario: Get all brands - Response status is always 200 even with no filters
  Given path '/brands'
  When method GET
  Then status 200
  And match response.statusCode == 200

Scenario: Get brand by ID - Verify brand slug is valid format
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0]._id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data.slug == '#regex ^[a-z0-9]+(?:-[a-z0-9]+)*$'

Scenario: Get all brands - Verify each brand has image URL
  Given path '/brands'
  When method GET
  Then status 200
  And match response.data[0].image == '#regex ^https?://'

Scenario: Get brand by ID - Multiple calls to same valid ID return consistent data
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0]._id
  * def firstCall
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  * def firstCall = response.data
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data == firstCall

Scenario: Get all brands - Response contains metadata
  Given path '/brands'
  When method GET
  Then status 200
  And match response.results >= 0
  And match response.paginationResult != null

Scenario: Get brand by ID - Response message is success
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0]._id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.message == '#string'

Scenario: Get all brands - Endpoint does not require authentication
  # Test that GET /brands works without token - no auth header needed
  Given path '/brands'
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get brand by ID - Endpoint does not require authentication
  # Test that GET /brands/{id} works without token
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0]._id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data._id == brandId

Scenario: Get all brands - Verify no sensitive data is exposed
  Given path '/brands'
  When method GET
  Then status 200
  And match response.data[0] !contains { password: '#notnull' }
  And match response.data[0] !contains { email: '#notnull' }
  And match response.data[0] !contains { secretKey: '#notnull' }

Scenario: Get brand by ID - Different valid brand IDs return different data
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId1 = response.data[0]._id
  * def brandId2 = response.data[1]._id
  Given path '/brands/' + brandId1
  When method GET
  Then status 200
  * def brand1Data = response.data
  Given path '/brands/' + brandId2
  When method GET
  Then status 200
  * def brand2Data = response.data
  And match brand1Data._id != brand2Data._id

Scenario: Get all brands - Empty results is valid response
  Given path '/brands'
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get brand by ID - Verify name is non-empty string
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0]._id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data.name != ''
  And match response.data.name != null

Scenario: Get all brands - Results count matches array length
  Given path '/brands'
  When method GET
  Then status 200
  And match response.results == response.data.length