# brands.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T03:38:35.172Z
# Feature: Brands
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Brands API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'

Scenario: Get all brands - happy path returns 200 with brand list
  # Tests GET /brands returns success with valid brand data
  Given path '/brands'
  When method GET
  Then status 200
  And match response.data == '#[]'
  And match response.results == '#number'

Scenario: Get brand by ID - happy path returns 200 with brand details
  # Tests GET /brands/{id} returns success with real fetched brand ID
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0]._id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data._id == brandId
  And match response.data.name == '#string'

Scenario: Get all brands with no auth token - returns 200 (no auth required)
  # Tests GET /brands without token header returns success (auth not required)
  Given path '/brands'
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get brand by ID with no auth token - returns 200 (no auth required)
  # Tests GET /brands/{id} without token header returns success (auth not required)
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0]._id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data._id == brandId

Scenario: Get brand by ID with invalid auth token - returns 200 (no auth required)
  # Tests GET /brands/{id} with invalid token header returns success (auth not required)
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0]._id
  And header token = 'invalid-token-xyz'
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data._id == brandId

Scenario: Get brand by ID with non-existent ID returns 404
  # Tests GET /brands/{id} with valid MongoDB format non-existent ID returns 404
  Given path '/brands/000000000000000000000000'
  When method GET
  Then status 404