# brands.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-21T13:28:18.756Z
# Feature: Brands
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Brands API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'

  # Login to get auth token for protected endpoints
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token

Scenario: Get all brands - Happy Path
  # Verify GET /brands returns 200 with list of brands
  Given path '/brands'
  When method GET
  Then status 200
  And match response.status == 200
  And match response.data == '#[]'
  And match response.data[0].id == '#string'
  And match response.data[0].name == '#string'
  And match response.data[0].image == '#string'

Scenario: Get all brands - Verify response structure
  # Verify all required fields are present in brand objects
  Given path '/brands'
  When method GET
  Then status 200
  And match response.data[0] contains { id: '#string', name: '#string', image: '#string' }
  And match response.pagination == '#object'

Scenario: Get all brands with pagination - Page parameter
  # Verify brands endpoint supports pagination
  Given path '/brands'
  And param page = 1
  When method GET
  Then status 200
  And match response.status == 200

Scenario: Get all brands with pagination - Limit parameter
  # Verify brands endpoint supports limit parameter
  Given path '/brands'
  And param limit = 10
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get brand by ID - Happy Path with valid MongoDB ID
  # Verify GET /brands/{id} returns 200 for valid brand ID
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0].id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.status == 200
  And match response.data.id == '#string'
  And match response.data.name == '#string'

Scenario: Get brand by ID - Valid format but non-existent ID
  # Verify GET /brands/{id} returns 404 when brand does not exist
  Given path '/brands/507f1f77bcf86cd799439099'
  When method GET
  Then status 404
  And match response.status == 404
  And match response.message == '#string'

Scenario: Get brand by ID - Invalid MongoDB ID format
  # Verify GET /brands/{id} returns 400 for malformed ID
  Given path '/brands/invalid-id-format'
  When method GET
  Then status 400
  And match response.status == 400

Scenario: Get brand by ID - Empty string as ID
  # Verify GET /brands/{id} returns 400 when ID is empty string
  Given path '/brands/'
  When method GET
  Then status 404

Scenario: Get brand by ID - All zeros MongoDB ID
  # Verify GET /brands/{id} returns 404 for valid format but non-existent ID
  Given path '/brands/000000000000000000000000'
  When method GET
  Then status 404
  And match response.status == 404

Scenario: Get all brands - Verify non-empty response list
  # Ensure the brands endpoint returns actual brand data
  Given path '/brands'
  When method GET
  Then status 200
  And match response.data != null
  And match response.data != '#[]'
  And match response.data[0].id != null
  And match response.data[0].name != null

Scenario: Get brand by ID - Case sensitivity of ID
  # Verify MongoDB IDs are case-sensitive
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0].id
  * def brandIdUppercase = brandId.toUpperCase()
  Given path '/brands/' + brandIdUppercase
  When method GET
  Then status 400 || status 404

Scenario: Get all brands - Boundary value large page number
  # Verify endpoint handles large page numbers gracefully
  Given path '/brands'
  And param page = 999999
  When method GET
  Then status 200
  And match response.status == 200
  And match response.data == '#[]'

Scenario: Get all brands - Boundary value zero page
  # Verify endpoint handles page 0
  Given path '/brands'
  And param page = 0
  When method GET
  Then status 200 || status 400

Scenario: Get all brands - Boundary value negative page
  # Verify endpoint rejects negative page numbers
  Given path '/brands'
  And param page = -1
  When method GET
  Then status 400 || status 200

Scenario: Get all brands - Boundary value with limit = 1
  # Verify endpoint respects minimum limit value
  Given path '/brands'
  And param limit = 1
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get all brands - Boundary value with very large limit
  # Verify endpoint handles large limit values
  Given path '/brands'
  And param limit = 999999999
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get all brands - Boundary value with negative limit
  # Verify endpoint rejects negative limit
  Given path '/brands'
  And param limit = -1
  When method GET
  Then status 400 || status 200

Scenario: Get all brands - Multiple query parameters
  # Verify endpoint handles multiple parameters together
  Given path '/brands'
  And param page = 1
  And param limit = 5
  When method GET
  Then status 200
  And match response.status == 200

Scenario: Get brand by ID - Verify brand data completeness
  # Ensure returned brand has all expected fields
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0].id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data contains { id: '#string', name: '#string', image: '#string' }
  And match response.data.id == '#notnull'
  And match response.data.name == '#notnull'
  And match response.data.image == '#notnull'

Scenario: Get brand by ID - Verify brand name is non-empty string
  # Ensure brand name is not empty
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0].id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data.name != ''
  And match response.data.name == '#string'

Scenario: Get brand by ID - Verify brand image is valid URL or path
  # Ensure brand image field exists and has content
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0].id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match response.data.image == '#string'
  And match response.data.image != ''

Scenario: Get all brands - Response headers validation
  # Verify response headers are properly set
  Given path '/brands'
  When method GET
  Then status 200
  And match responseHeaders['content-type'] contains 'application/json'

Scenario: Get brand by ID - Response headers validation
  # Verify response headers for single brand endpoint
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0].id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And match responseHeaders['content-type'] contains 'application/json'

Scenario: Get all brands - Verify response time is acceptable
  # Ensure API responds within reasonable time
  Given path '/brands'
  When method GET
  Then status 200
  And assert responseTime < 5000

Scenario: Get brand by ID - Verify response time is acceptable
  # Ensure single brand endpoint responds quickly
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0].id
  Given path '/brands/' + brandId
  When method GET
  Then status 200
  And assert responseTime < 5000

Scenario: Get all brands - Verify consistent data across calls
  # Ensure multiple calls return consistent data
  Given path '/brands'
  When method GET
  Then status 200
  * def firstCall = response.data
  Given path '/brands'
  When method GET
  Then status 200
  * def secondCall = response.data
  And match firstCall[0].id == secondCall[0].id

Scenario: Get brand by ID - Brand ID matches expected format
  # Verify brand IDs are valid MongoDB ObjectIds (24 hex chars)
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0].id
  * def idLength = brandId.length
  And assert idLength == 24

Scenario: Get all brands - Verify no duplicate brands
  # Ensure brands list contains unique entries
  Given path '/brands'
  When method GET
  Then status 200
  * def brandIds = response.data[*].id
  * def uniqueIds = karate.call('classpath:features/utils.feature@getUniqueCount', brandIds)
  And assert uniqueIds == brandIds.length || brandIds.length < 2

Scenario: Get brand by ID - Special characters in ID handling
  # Verify endpoint properly handles special characters in ID
  Given path '/brands/507f-1f77-bcf8-6cd7-9943-9011'
  When method GET
  Then status 400

Scenario: Get all brands - Null response validation
  # Verify response is never null
  Given path '/brands'
  When method GET
  Then status 200
  And match response != null
  And match response.data != null

Scenario: Get brand by ID - Query string with extra parameters
  # Verify endpoint ignores unknown parameters
  Given path '/brands'
  When method GET
  Then status 200
  * def brandId = response.data[0].id
  Given path '/brands/' + brandId
  And param unknownParam = 'test'
  When method GET
  Then status 200 || status 400

Scenario: Get all brands - SQL injection attempt in query parameter
  # Verify endpoint is safe from SQL injection
  Given path '/brands'
  And param page = "1; DROP TABLE brands; --"
  When method GET
  Then status 200 || status 400

Scenario: Get brand by ID - XSS attempt in ID parameter
  # Verify endpoint sanitizes input
  Given path '/brands/<script>alert(1)</script>'
  When method GET
  Then status 400 || status 404

Scenario: Get all brands - Very long string parameter value
  # Verify endpoint handles extremely long parameter values
  * def longString = karate.repeat('a', 10000)
  Given path '/brands'
  And param page = longString
  When method GET
  Then status 200 || status 400