# cart.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T02:56:28.359Z
# Feature: Cart
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Cart API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'
  
  # Login to get authToken and userId
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  * def userId = response.user._id
  
  # Fetch a real product ID for cart operations
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0].id

# ==================== GET CART TESTS ====================

Scenario: Get cart - Happy path with valid token
  # Retrieve user's cart items
  Given path '/cart'
  And header token = authToken
  When method GET
  Then status 200
  And match response.status == 'success'

Scenario: Get cart - Without token returns 401
  # Expect 401 when no token provided
  Given path '/cart'
  When method GET
  Then status 401
  And match response.message contains 'token'

Scenario: Get cart - With invalid token returns 401
  # Expect 401 with malformed token
  Given path '/cart'
  And header token = 'invalid-token-xyz'
  When method GET
  Then status 401

# ==================== POST CART TESTS ====================

Scenario: Add product to cart - Happy path with valid product
  # Add a real product to cart
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  And match response.status == 'success'
  And match response.message contains 'cart'

Scenario: Add product to cart - Without token returns 401
  # Expect 401 when no token provided
  Given path '/cart'
  And request { "productId": "#(productId)" }
  When method POST
  Then status 401

Scenario: Add product to cart - With invalid token returns 401
  # Expect 401 with malformed token
  Given path '/cart'
  And header token = 'invalid-token'
  And request { "productId": "#(productId)" }
  When method POST
  Then status 401

Scenario: Add product to cart - Missing required productId field
  # Expect 400 when productId is omitted
  Given path '/cart'
  And header token = authToken
  And request {}
  When method POST
  Then status 400

Scenario: Add product to cart - Invalid product ID format
  # Non-existent MongoDB ID returns 404
  Given path '/cart'
  And header token = authToken
  And request { "productId": '000000000000000000000000' }
  When method POST
  Then status 404

Scenario: Add product to cart - Invalid ObjectId format returns 500
  # Malformed ID format triggers 500
  Given path '/cart'
  And header token = authToken
  And request { "productId": "invalid-id" }
  When method POST
  Then status 500

Scenario: Add product to cart - ProductId with wrong data type
  # Send numeric ID instead of string
  Given path '/cart'
  And header token = authToken
  And request { "productId": 12345 }
  When method POST
  Then status 400 || status 500

# ==================== DELETE CART TESTS ====================

Scenario: Clear cart - Happy path removes all items
  # First add product to ensure cart is not empty
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  
  # Now clear the entire cart
  Given path '/cart'
  And header token = authToken
  When method DELETE
  Then status 204

Scenario: Clear cart - Without token returns 401
  # Expect 401 when no token provided
  Given path '/cart'
  When method DELETE
  Then status 401

Scenario: Clear cart - With invalid token returns 401
  # Expect 401 with malformed token
  Given path '/cart'
  And header token = 'invalid-token'
  When method DELETE
  Then status 401

# ==================== PUT CART ITEM TESTS ====================

Scenario: Update cart item quantity - Happy path
  # First add product to cart
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  * def itemId = response.data.cartItems[0]._id
  
  # Update quantity of the added item
  Given path '/cart/' + itemId
  And header token = authToken
  And request { "count": 3 }
  When method PUT
  Then status 200
  And match response.status == 'success'

Scenario: Update cart item quantity - Without token returns 401
  # Add item first to get itemId
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  * def itemId = response.data.cartItems[0]._id
  
  # Try update without token
  Given path '/cart/' + itemId
  And request { "count": 2 }
  When method PUT
  Then status 401

Scenario: Update cart item quantity - With invalid token returns 401
  # Add item first to get itemId
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  * def itemId = response.data.cartItems[0]._id
  
  # Try update with invalid token
  Given path '/cart/' + itemId
  And header token = 'invalid-token'
  And request { "count": 2 }
  When method PUT
  Then status 401

Scenario: Update cart item quantity - Missing required count field
  # Add item first to get itemId
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  * def itemId = response.data.cartItems[0]._id
  
  # Try update without count
  Given path '/cart/' + itemId
  And header token = authToken
  And request {}
  When method PUT
  Then status 400

Scenario: Update cart item quantity - Invalid count value
  # Add item first to get itemId
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  * def itemId = response.data.cartItems[0]._id
  
  # Try update with invalid count
  Given path '/cart/' + itemId
  And header token = authToken
  And request { "count": -5 }
  When method PUT
  Then status 400

Scenario: Update cart item quantity - Non-existent item ID returns 404
  # Try to update item that does not exist
  Given path '/cart/000000000000000000000000'
  And header token = authToken
  And request { "count": 2 }
  When method PUT
  Then status 404

Scenario: Update cart item quantity - Invalid itemId format returns 500
  # Malformed item ID format
  Given path '/cart/invalid-id'
  And header token = authToken
  And request { "count": 2 }
  When method PUT
  Then status 500

# ==================== DELETE CART ITEM TESTS ====================

Scenario: Remove item from cart - Happy path
  # First add product to cart
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  * def itemId = response.data.cartItems[0]._id
  
  # Remove the item from cart
  Given path '/cart/' + itemId
  And header token = authToken
  When method DELETE
  Then status 200
  And match response.status == 'success'

Scenario: Remove item from cart - Without token returns 401
  # Add item first to get itemId
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  * def itemId = response.data.cartItems[0]._id
  
  # Try delete without token
  Given path '/cart/' + itemId
  When method DELETE
  Then status 401

Scenario: Remove item from cart - With invalid token returns 401
  # Add item first to get itemId
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  * def itemId = response.data.cartItems[0]._id
  
  # Try delete with invalid token
  Given path '/cart/' + itemId
  And header token = 'invalid-token'
  When method DELETE
  Then status 401

Scenario: Remove item from cart - Non-existent item ID returns 404
  # Try to delete item that does not exist
  Given path '/cart/000000000000000000000000'
  And header token = authToken
  When method DELETE
  Then status 404

Scenario: Remove item from cart - Invalid itemId format returns 500
  # Malformed item ID format
  Given path '/cart/invalid-id'
  And header token = authToken
  When method DELETE
  Then status 500