# cart.feature - AUTO-GENERATED by karate-generator.py (Python + Groq FREE)
# Generated: 2026-05-22T08:59:11.963179
# Feature: Cart
# API: https://ecommerce.routemisr.com/api/v1
# Uses REAL API discovery - status codes verified against live API

Feature: RetailShop Cart API
  Background:
    * url 'https://ecommerce.routemisr.com/api/v1'
    * def testEmail = 'qelead.test2026@gmail.com'
    * def testPassword = 'QeTest@2026'
    Given path '/auth/signin'
    And request { "email": "#(testEmail)", "password": "#(testPassword)" }
    When method POST
    Then status 200
    * def authToken = response.token
    * def userId = response.user._id

  Scenario: Get logged in user cart - Happy Path
    Given path '/cart'
    And header token = authToken
    When method GET
    Then status 200

  Scenario: Get logged in user cart - No Auth Token
    Given path '/cart'
    When method GET
    Then status 401
    And match response == { message: "You are not logged in. Please login to get access" }

  Scenario: Get logged in user cart - Invalid Auth Token
    Given path '/cart'
    And header token = 'invalid-token-xyz'
    When method GET
    Then status 401

  Scenario: Get logged in user cart - Not Found
    Given path '/cart'
    And header token = authToken
    When method GET
    Then status 404

  Scenario: Add product to cart - Happy Path
    Given path '/cart'
    And header token = authToken
    And request { "productId": "6428ebc6dc1175abc65ca0b9" }
    When method POST
    Then status 200

  Scenario: Add product to cart - No Auth Token
    Given path '/cart'
    And request { "productId": "6428ebc6dc1175abc65ca0b9" }
    When method POST
    Then status 401
    And match response == { message: "You are not logged in. Please login to get access" }

  Scenario: Add product to cart - Invalid Auth Token
    Given path '/cart'
    And header token = 'invalid-token-xyz'
    And request { "productId": "6428ebc6dc1175abc65ca0b9" }
    When method POST
    Then status 401

  Scenario: Add product to cart - Missing Required Fields
    Given path '/cart'
    And header token = authToken
    When method POST
    Then status 400

  Scenario: Add product to cart - Invalid Product ID
    Given path '/cart'
    And header token = authToken
    And request { "productId": "invalid-id" }
    When method POST
    Then status 400

  Scenario: Add product to cart - Non-existent Product ID
    Given path '/cart'
    And header token = authToken
    And request { "productId": "000000000000000000000000" }
    When method POST
    Then status 404

  Scenario: Clear all cart items - Happy Path
    Given path '/cart'
    And header token = authToken
    When method DELETE
    Then status 204

  Scenario: Clear all cart items - No Auth Token
    Given path '/cart'
    When method DELETE
    Then status 401
    And match response == { message: "You are not logged in. Please login to get access" }

  Scenario: Clear all cart items - Invalid Auth Token
    Given path '/cart'
    And header token = 'invalid-token-xyz'
    When method DELETE
    Then status 401

  Scenario: Update cart item quantity - Happy Path
    Given path '/cart/6428ebc6dc1175abc65ca0b9'
    And header token = authToken
    And request { "count": 2 }
    When method PUT
    Then status 200

  Scenario: Update cart item quantity - No Auth Token
    Given path '/cart/6428ebc6dc1175abc65ca0b9'
    And request { "count": 2 }
    When method PUT
    Then status 401
    And match response == { message: "You are not logged in. Please login to get access" }

  Scenario: Update cart item quantity - Invalid Auth Token
    Given path '/cart/6428ebc6dc1175abc65ca0b9'
    And header token = 'invalid-token-xyz'
    And request { "count": 2 }
    When method PUT
    Then status 401

  Scenario: Update cart item quantity - Missing Required Fields
    Given path '/cart/6428ebc6dc1175abc65ca0b9'
    And header token = authToken
    When method PUT
    Then status 400

  Scenario: Update cart item quantity - Invalid Count
    Given path '/cart/6428ebc6dc1175abc65ca0b9'
    And header token = authToken
    And request { "count": "invalid-count" }
    When method PUT
    Then status 400

  Scenario: Update cart item quantity - Item Not Found
    Given path '/cart/000000000000000000000000'
    And header token = authToken
    And request { "count": 2 }
    When method PUT
    Then status 404

  Scenario: Remove specific item from cart - Happy Path
    Given path '/cart/6428ebc6dc1175abc65ca0b9'
    And header token = authToken
    When method DELETE
    Then status 200

  Scenario: Remove specific item from cart - No Auth Token
    Given path '/cart/6428ebc6dc1175abc65ca0b9'
    When method DELETE
    Then status 401
    And match response == { message: "You are not logged in. Please login to get access" }

  Scenario: Remove specific item from cart - Invalid Auth Token
    Given path '/cart/6428ebc6dc1175abc65ca0b9'
    And header token = 'invalid-token-xyz'
    When method DELETE
    Then status 401

  Scenario: Remove specific item from cart - Item Not Found
    Given path '/cart/000000000000000000000000'
    And header token = authToken
    When method DELETE
    Then status 404