# cart.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T03:38:44.734Z
# Feature: Cart
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Cart API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'

Scenario: Get Cart - Happy Path with valid auth token
  # Test getting user cart successfully with valid authentication
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/cart'
  And header token = authToken
  When method GET
  Then status 200
  And match response.status == 'success'

Scenario: Get Cart - No auth token returns 401
  # Test that missing token header returns 401 Unauthorized
  Given path '/cart'
  When method GET
  Then status 401

Scenario: Get Cart - Invalid auth token returns 401
  # Test that invalid token returns 401 Unauthorized
  Given path '/cart'
  And header token = 'invalid-token-xyz'
  When method GET
  Then status 401

Scenario: Add Product to Cart - Happy Path with real product
  # Test adding product to cart successfully with valid data
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  And match response.status == 'success'

Scenario: Add Product to Cart - No auth token returns 401
  # Test that missing token header returns 401 when adding to cart
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/cart'
  And request { "productId": "#(productId)" }
  When method POST
  Then status 401

Scenario: Add Product to Cart - Invalid auth token returns 401
  # Test that invalid token returns 401 when adding to cart
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/cart'
  And header token = 'invalid-token-xyz'
  And request { "productId": "#(productId)" }
  When method POST
  Then status 401

Scenario: Add Product to Cart - Missing productId returns 400
  # Test that missing productId in request body returns 400
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/cart'
  And header token = authToken
  And request { }
  When method POST
  Then status 400

Scenario: Add Product to Cart - Invalid product ID returns 400
  # Test that invalid product ID format returns 400
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/cart'
  And header token = authToken
  And request { "productId": "invalid" }
  When method POST
  Then status 400

Scenario: Clear Cart - Happy Path with valid auth token
  # Test clearing all cart items successfully with valid authentication
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/cart'
  And header token = authToken
  When method DELETE
  Then status 204

Scenario: Clear Cart - No auth token returns 401
  # Test that missing token header returns 401 when clearing cart
  Given path '/cart'
  When method DELETE
  Then status 401

Scenario: Clear Cart - Invalid auth token returns 401
  # Test that invalid token returns 401 when clearing cart
  Given path '/cart'
  And header token = 'invalid-token-xyz'
  When method DELETE
  Then status 401

Scenario: Update Cart Item Quantity - Happy Path with real item
  # Test updating cart item quantity successfully with valid data
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  * def itemId = response.data._id
  Given path '/cart/' + itemId
  And header token = authToken
  And request { "count": 3 }
  When method PUT
  Then status 200
  And match response.status == 'success'

Scenario: Update Cart Item Quantity - No auth token returns 401
  # Test that missing token header returns 401 when updating quantity
  Given path '/cart/000000000000000000000000'
  And request { "count": 3 }
  When method PUT
  Then status 401

Scenario: Update Cart Item Quantity - Invalid auth token returns 401
  # Test that invalid token returns 401 when updating quantity
  Given path '/cart/000000000000000000000000'
  And header token = 'invalid-token-xyz'
  And request { "count": 3 }
  When method PUT
  Then status 401

Scenario: Update Cart Item Quantity - Missing count returns 400
  # Test that missing count in request body returns 400
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/cart/000000000000000000000000'
  And header token = authToken
  And request { }
  When method PUT
  Then status 400

Scenario: Update Cart Item Quantity - Non-existent item returns 404
  # Test that updating non-existent cart item returns 404
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/cart/000000000000000000000000'
  And header token = authToken
  And request { "count": 3 }
  When method PUT
  Then status 404

Scenario: Remove Cart Item - Happy Path with real item
  # Test removing cart item successfully with valid authentication
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  * def itemId = response.data._id
  Given path '/cart/' + itemId
  And header token = authToken
  When method DELETE
  Then status 200
  And match response.status == 'success'

Scenario: Remove Cart Item - No auth token returns 401
  # Test that missing token header returns 401 when removing item
  Given path '/cart/000000000000000000000000'
  When method DELETE
  Then status 401

Scenario: Remove Cart Item - Invalid auth token returns 401
  # Test that invalid token returns 401 when removing item
  Given path '/cart/000000000000000000000000'
  And header token = 'invalid-token-xyz'
  When method DELETE
  Then status 401

Scenario: Remove Cart Item - Non-existent item returns 404
  # Test that removing non-existent cart item returns 404
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/cart/000000000000000000000000'
  And header token = authToken
  When method DELETE
  Then status 404