# categories.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T02:56:07.222Z
# Feature: Categories
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Categories API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'

Scenario: Get all categories - Happy path returns 200 with list of categories
  # Test that the GET /categories endpoint returns all categories successfully
  Given path '/categories'
  When method GET
  Then status 200
  And match response.data == '#[]'
  And match response.data[0]._id == '#string'
  And match response.data[0].name == '#string'
  And match response.data[0].slug == '#string'

Scenario: Get all categories - Verify response structure contains expected fields
  # Validate that category objects have all required fields
  Given path '/categories'
  When method GET
  Then status 200
  And match response.data[*]._id == '#[]'
  And match response.data[*].name == '#[]'
  And match response.data[*].slug == '#[]'

Scenario: Get category by ID - Happy path returns 200 with specific category
  # Test that a specific category can be retrieved by its ID
  # First, fetch a real category ID from the list
  Given path '/categories'
  When method GET
  Then status 200
  * def categoryId = response.data[0]._id
  
  # Now test getting that specific category
  Given path '/categories/' + categoryId
  When method GET
  Then status 200
  And match response.data._id == categoryId
  And match response.data.name == '#string'
  And match response.data.slug == '#string'

Scenario: Get category by ID - Non-existent valid MongoDB ID returns 404
  # Test that requesting a category with a valid MongoDB ID format that doesn't exist returns 404
  Given path '/categories/000000000000000000000000'
  When method GET
  Then status 404
  And match response.message != null

Scenario: Get category by ID - Invalid ID format returns 500
  # Test that an invalid ObjectId format in the path returns 500
  Given path '/categories/invalid-id-format'
  When method GET
  Then status 500

Scenario: Get category by ID - Empty string ID returns 500
  # Test that an empty string as category ID returns 500
  Given path '/categories/'
  When method GET
  Then status 404

Scenario: Get category by ID - Special characters in ID returns 500
  # Test that special characters in ID parameter returns 500
  Given path '/categories/!!@@##$$%%'
  When method GET
  Then status 500

Scenario: Get all categories - Verify endpoint is public (no auth required)
  # Test that categories endpoint works without authentication token
  Given path '/categories'
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get category by ID - Verify endpoint is public (no auth required)
  # Test that getting a specific category works without authentication token
  Given path '/categories'
  When method GET
  Then status 200
  * def categoryId = response.data[0]._id
  
  Given path '/categories/' + categoryId
  When method GET
  Then status 200
  And match response.data._id == categoryId

Scenario: Get all categories - Verify response has correct HTTP headers
  # Test that response returns proper content-type header
  Given path '/categories'
  When method GET
  Then status 200
  And match response.data != null

Scenario: Get category by ID - Numeric ID returns 500
  # Test that a purely numeric ID returns 500 as it's not a valid MongoDB ObjectId format
  Given path '/categories/123456789012345678901234'
  When method GET
  Then status 200 || status 404

Scenario: Get all categories - Multiple calls return consistent data
  # Test that calling the endpoint multiple times returns the same data
  Given path '/categories'
  When method GET
  Then status 200
  * def firstCall = response.data
  
  Given path '/categories'
  When method GET
  Then status 200
  * def secondCall = response.data
  And match firstCall == secondCall

Scenario: Get category by ID - Real category has valid structure
  # Test that fetched category has all expected properties with correct types
  Given path '/categories'
  When method GET
  Then status 200
  * def categoryId = response.data[0]._id
  
  Given path '/categories/' + categoryId
  When method GET
  Then status 200
  And match response.data._id == '#string'
  And match response.data.name == '#string'
  And match response.data.slug == '#string'
  And match response.data._id.length() == 24

Scenario: Get all categories - Response contains at least one category
  # Test that the categories list is not empty
  Given path '/categories'
  When method GET
  Then status 200
  And match response.data.length() > 0

Scenario: Get category by ID - Uppercase ObjectId returns 500 or 404
  # Test that uppercase letters in ObjectId format still return error
  Given path '/categories/ABCDEF1234567890ABCDEF12'
  When method GET
  Then status 404 || status 500

Scenario: Get category by ID - Mixed case ObjectId with special char returns 500
  # Test edge case of mixed format ID
  Given path '/categories/507f1f77-bcf8-6cd7-9943-9011'
  When method GET
  Then status 500