# categories.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T03:38:31.393Z
# Feature: Categories
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Categories API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'

Scenario: Get all categories - Happy path returns success with category list
  Given path '/categories'
  When method GET
  Then status 200
  And match response.data == '#[]'
  And match response.data[0] contains { _id: '#string', name: '#string' }
  * def categoryId = response.data[0]._id

Scenario: Get category by ID - Happy path with real fetched category ID returns success
  Given path '/categories'
  When method GET
  Then status 200
  * def categoryId = response.data[0]._id
  Given path '/categories/' + categoryId
  When method GET
  Then status 200
  And match response.data contains { _id: '#string', name: '#string' }

Scenario: Get category by ID - Invalid auth token returns 401
  Given path '/categories'
  When method GET
  Then status 200
  * def categoryId = response.data[0]._id
  Given path '/categories/' + categoryId
  And header token = 'invalid-token-xyz'
  When method GET
  Then status 401

Scenario: Get all categories - No auth token header returns 401
  Given path '/categories'
  And header token = null
  When method GET
  Then status 401

Scenario: Get category by ID - Non-existent MongoDB ID returns 404
  Given path '/categories/000000000000000000000000'
  When method GET
  Then status 404