# categories.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-21T13:28:02.519Z
# Feature: Categories
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Categories API
  
  Background:
    * url 'https://ecommerce.routemisr.com/api/v1'
    * def testEmail = 'qelead.test2026@gmail.com'
    * def testPassword = 'QeTest@2026'
    * def validCategoryId = '507f1f77bcf86cd799439011'
    * def nonExistentCategoryId = '507f1f77bcf86cd799439099'
    * def invalidCategoryId = '000000000000000000000000'
    * def malformedCategoryId = 'invalid-id-format'

  # HAPPY PATH SCENARIOS
  Scenario: Get all categories successfully returns list with 200 status
    Given path '/categories'
    When method GET
    Then status 200
    And match response != null
    And match response.data == '#[]'

  Scenario: Get all categories returns data array with category objects
    Given path '/categories'
    When method GET
    Then status 200
    And match response.data[0].name == '#string'
    And match response.data[0]._id == '#string'

  Scenario: Get category by valid ID returns 200 with category details
    Given path '/categories/' + validCategoryId
    When method GET
    Then status 200
    And match response.data != null
    And match response.data._id == '#string'
    And match response.data.name == '#string'

  # ERROR SCENARIOS - DOCUMENTED CODES
  Scenario: Get category by non-existent ID returns 404 not found
    Given path '/categories/' + nonExistentCategoryId
    When method GET
    Then status 404
    And match response.message != null

  Scenario: Get category with malformed ID format returns 404
    Given path '/categories/' + malformedCategoryId
    When method GET
    Then status 404

  Scenario: Get category with invalid MongoDB ID returns 404
    Given path '/categories/' + invalidCategoryId
    When method GET
    Then status 404

  # INVALID DATA TYPE SCENARIOS
  Scenario: Get category with numeric ID string in path returns 404
    Given path '/categories/12345'
    When method GET
    Then status 404

  Scenario: Get category with special characters in ID returns 404
    Given path '/categories/!@#$%^&*()'
    When method GET
    Then status 404

  Scenario: Get category with extremely long ID string returns 404
    * def longId = 'a' + java.lang.String.valueOf(java.lang.Math.random()).substring(2)
    Given path '/categories/' + longId
    When method GET
    Then status 404

  # BOUNDARY VALUE SCENARIOS
  Scenario: Get category with empty string ID in path returns error
    Given path '/categories/'
    When method GET
    Then status 404

  Scenario: Get all categories with pagination parameter page 1
    Given path '/categories'
    And param page = 1
    When method GET
    Then status 200
    And match response.data == '#[]'

  Scenario: Get all categories with pagination parameter page 0
    Given path '/categories'
    And param page = 0
    When method GET
    Then status 200

  Scenario: Get all categories with negative pagination parameter
    Given path '/categories'
    And param page = -1
    When method GET
    Then status 200

  Scenario: Get all categories with very large page number
    Given path '/categories'
    And param page = 999999
    When method GET
    Then status 200

  Scenario: Get all categories with string value for page parameter
    Given path '/categories'
    And param page = 'abc'
    When method GET
    Then status 200

  Scenario: Get all categories with decimal page parameter
    Given path '/categories'
    And param page = 1.5
    When method GET
    Then status 200

  # SPECIAL CHARACTER & ENCODING SCENARIOS
  Scenario: Get all categories with special characters in query parameter
    Given path '/categories'
    And param search = '!@#$%^&*()'
    When method GET
    Then status 200

  Scenario: Get all categories with unicode characters in query
    Given path '/categories'
    And param search = 'مقولة'
    When method GET
    Then status 200

  Scenario: Get all categories with SQL injection attempt in query
    Given path '/categories'
    And param search = "'; DROP TABLE categories; --"
    When method GET
    Then status 200

  # RESPONSE VALIDATION SCENARIOS
  Scenario: Get all categories response structure validation
    Given path '/categories'
    When method GET
    Then status 200
    And match response.message == '#string'
    And match response.data == '#[]'

  Scenario: Get category by ID response contains required fields
    Given path '/categories/' + validCategoryId
    When method GET
    Then status 200
    And match response.data._id == '#string'
    And match response.data.name == '#string'
    And match response.data.slug == '#string'
    And match response.data.image == '#string'

  # WHITESPACE & FORMATTING SCENARIOS
  Scenario: Get category with spaces in path parameter
    Given path '/categories/%20%20'
    When method GET
    Then status 404

  Scenario: Get all categories with whitespace in query parameter
    Given path '/categories'
    And param search = '   '
    When method GET
    Then status 200

  # CASE SENSITIVITY SCENARIOS
  Scenario: Get all categories endpoint is case sensitive GET method
    Given path '/categories'
    When method GET
    Then status 200

  # MULTIPLE QUERY PARAMETERS
  Scenario: Get all categories with multiple pagination parameters
    Given path '/categories'
    And param page = 1
    And param limit = 10
    When method GET
    Then status 200
    And match response.data == '#[]'

  Scenario: Get all categories with limit parameter zero
    Given path '/categories'
    And param limit = 0
    When method GET
    Then status 200

  Scenario: Get all categories with negative limit parameter
    Given path '/categories'
    And param limit = -5
    When method GET
    Then status 200

  Scenario: Get all categories with very large limit parameter
    Given path '/categories'
    And param limit = 999999
    When method GET
    Then status 200

  # NULL AND UNDEFINED HANDLING
  Scenario: Get category with null value encoded in ID returns 404
    Given path '/categories/null'
    When method GET
    Then status 404

  Scenario: Get category with undefined string in ID returns 404
    Given path '/categories/undefined'
    When method GET
    Then status 404

  # CONSECUTIVE REQUESTS
  Scenario: Get all categories twice in sequence returns consistent results
    Given path '/categories'
    When method GET
    Then status 200
    * def firstResponse = response.data
    
    Given path '/categories'
    When method GET
    Then status 200
    And match response.data == firstResponse

  # RESPONSE TIME IMPLICIT TEST
  Scenario: Get all categories completes within reasonable time
    Given path '/categories'
    When method GET
    Then status 200
    And assert responseTime < 5000

  # EMPTY RESULT SCENARIOS
  Scenario: Get category with ID that exists returns non-empty data
    Given path '/categories/' + validCategoryId
    When method GET
    Then status 200
    And match response.data != null
    And match response.data != ''

  # DOUBLE SLASH IN PATH
  Scenario: Get categories with double slash in path returns response
    Given path '/categories//' + validCategoryId
    When method GET
    Then status 404

  # TRAILING SLASH
  Scenario: Get all categories with trailing slash returns 200
    Given path '/categories/'
    When method GET
    Then status 200

  Scenario: Get category by ID with trailing slash returns response
    Given path '/categories/' + validCategoryId + '/'
    When method GET
    Then status 200 || status 404

  # ENCODING SCENARIOS
  Scenario: Get category with URL encoded ID returns response
    Given path '/categories/%50%30%37%66%31%66%37%37'
    When method GET
    Then status 404

  # CONCURRENT-LIKE SCENARIOS
  Scenario: Get all categories and single category in sequence
    Given path '/categories'
    When method GET
    Then status 200
    * def allCategories = response.data
    
    Given path '/categories/' + validCategoryId
    When method GET
    Then status 200
    And match response.data._id == '#string'

  # TYPE COERCION SCENARIOS
  Scenario: Get category with boolean-like ID string
    Given path '/categories/true'
    When method GET
    Then status 404

  Scenario: Get category with boolean false as ID
    Given path '/categories/false'
    When method GET
    Then status 404

  # ARRAY-LIKE ID SCENARIOS
  Scenario: Get categories endpoint ignores array-like parameters gracefully
    Given path '/categories'
    And param ids = '1,2,3'
    When method GET
    Then status 200

  # ERROR MESSAGE VALIDATION
  Scenario: Get non-existent category returns descriptive error message
    Given path '/categories/' + nonExistentCategoryId
    When method GET
    Then status 404
    And match response.message != null
    And match response.message == '#string'