# inventory.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-21T01:47:47.327Z
# Feature: Inventory
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts
# Review scenarios before running against real API

Feature: RetailShop Inventory API

Background:
  * url 'https://api.retailshop.com/v1'
  * def authToken = 'Bearer test-token-12345'
  * def adminToken = 'Bearer admin-token-67890'
  * def invalidToken = 'Bearer invalid-token-xyz'

Scenario: Get inventory - happy path with valid token
  Given path '/inventory/101'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response.productId == 101
  And match response.stock == '#number'
  And match response.stock >= 0

Scenario: Get inventory - product exists with stock data
  Given path '/inventory/205'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response != null
  And match response.productId == '#number'
  And match response.inStock == '#boolean'
  And match response.lastUpdated == '#string'

Scenario: Get inventory - missing authorization header returns 401
  Given path '/inventory/101'
  When method GET
  Then status 401
  And match response.error == 'Unauthorized'

Scenario: Get inventory - invalid token returns 401
  Given path '/inventory/101'
  And header Authorization = invalidToken
  When method GET
  Then status 401
  And match response.message contains 'Invalid token'

Scenario: Get inventory - expired token returns 401
  Given path '/inventory/101'
  And header Authorization = 'Bearer expired-token-old'
  When method GET
  Then status 401

Scenario: Get inventory - product not found returns 404
  Given path '/inventory/999999'
  And header Authorization = authToken
  When method GET
  Then status 404
  And match response.error == 'Product not found'
  And match response.productId == 999999

Scenario: Get inventory - non-numeric product ID returns 404
  Given path '/inventory/abc123'
  And header Authorization = authToken
  When method GET
  Then status 404

Scenario: Get inventory - invalid product ID format
  Given path '/inventory/!@#$'
  And header Authorization = authToken
  When method GET
  Then status 400

Scenario: Get inventory - negative product ID
  Given path '/inventory/-5'
  And header Authorization = authToken
  When method GET
  Then status 404

Scenario: Get inventory - zero product ID
  Given path '/inventory/0'
  And header Authorization = authToken
  When method GET
  Then status 404

Scenario: Get inventory - very large product ID
  Given path '/inventory/2147483647'
  And header Authorization = authToken
  When method GET
  Then status 404

Scenario: Update inventory - happy path with admin token
  Given path '/inventory/102'
  And header Authorization = adminToken
  And request { "stock": 150 }
  When method PUT
  Then status 200
  And match response.productId == 102
  And match response.stock == 150
  And match response.updated == '#string'

Scenario: Update inventory - successful stock update returns confirmation
  Given path '/inventory/303'
  And header Authorization = adminToken
  And request { "stock": 75 }
  When method PUT
  Then status 200
  And match response.message contains 'updated'
  And match response.previousStock == '#number'
  And match response.newStock == 75

Scenario: Update inventory - missing stock field returns 400
  Given path '/inventory/102'
  And header Authorization = adminToken
  And request {}
  When method PUT
  Then status 400
  And match response.error contains 'stock'

Scenario: Update inventory - stock field null returns 400
  Given path '/inventory/102'
  And header Authorization = adminToken
  And request { "stock": null }
  When method PUT
  Then status 400

Scenario: Update inventory - stock as string instead of number returns 400
  Given path '/inventory/102'
  And header Authorization = adminToken
  And request { "stock": "150" }
  When method PUT
  Then status 400

Scenario: Update inventory - negative stock value returns 400
  Given path '/inventory/102'
  And header Authorization = adminToken
  And request { "stock": -10 }
  When method PUT
  Then status 400
  And match response.error contains 'Invalid'

Scenario: Update inventory - stock value exceeds max returns 400
  Given path '/inventory/102'
  And header Authorization = adminToken
  And request { "stock": 999999999 }
  When method PUT
  Then status 400

Scenario: Update inventory - decimal stock value returns 400
  Given path '/inventory/102'
  And header Authorization = adminToken
  And request { "stock": 150.5 }
  When method PUT
  Then status 400
  And match response.error contains 'integer'

Scenario: Update inventory - zero stock value is valid
  Given path '/inventory/102'
  And header Authorization = adminToken
  And request { "stock": 0 }
  When method PUT
  Then status 200
  And match response.stock == 0

Scenario: Update inventory - missing authorization header returns 401
  Given path '/inventory/102'
  And request { "stock": 150 }
  When method PUT
  Then status 401
  And match response.error == 'Unauthorized'

Scenario: Update inventory - invalid token returns 401
  Given path '/inventory/102'
  And header Authorization = invalidToken
  And request { "stock": 150 }
  When method PUT
  Then status 401

Scenario: Update inventory - user token without admin role returns 403
  Given path '/inventory/102'
  And header Authorization = authToken
  And request { "stock": 150 }
  When method PUT
  Then status 403
  And match response.error contains 'admin'

Scenario: Update inventory - non-admin user forbidden
  Given path '/inventory/102'
  And header Authorization = 'Bearer user-token-basic'
  And request { "stock": 200 }
  When method PUT
  Then status 403
  And match response.message contains 'Admin'

Scenario: Update inventory - product not found returns 404
  Given path '/inventory/999999'
  And header Authorization = adminToken
  And request { "stock": 150 }
  When method PUT
  Then status 404
  And match response.error == 'Product not found'

Scenario: Update inventory - non-numeric product ID returns 404
  Given path '/inventory/invalid'
  And header Authorization = adminToken
  And request { "stock": 150 }
  When method PUT
  Then status 404

Scenario: Update inventory - extra fields in request body are ignored
  Given path '/inventory/102'
  And header Authorization = adminToken
  And request { "stock": 150, "extra": "field", "debug": true }
  When method PUT
  Then status 200
  And match response.stock == 150

Scenario: Update inventory - empty stock object returns 400
  Given path '/inventory/102'
  And header Authorization = adminToken
  And request { "stock": {} }
  When method PUT
  Then status 400

Scenario: Update inventory - stock as boolean returns 400
  Given path '/inventory/102'
  And header Authorization = adminToken
  And request { "stock": true }
  When method PUT
  Then status 400

Scenario: Update inventory - stock as array returns 400
  Given path '/inventory/102'
  And header Authorization = adminToken
  And request { "stock": [150] }
  When method PUT
  Then status 400

Scenario: Update inventory - whitespace in token is invalid
  Given path '/inventory/102'
  And header Authorization = '  Bearer test-token-12345  '
  And request { "stock": 150 }
  When method PUT
  Then status 401

Scenario: Update inventory - case sensitive token check
  Given path '/inventory/102'
  And header Authorization = 'bearer test-token-12345'
  And request { "stock": 150 }
  When method PUT
  Then status 401

Scenario: Get inventory - valid product ID returns complete response structure
  Given path '/inventory/104'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response contains { productId: '#number', stock: '#number' }
  And match response.productId == 104

Scenario: Update inventory - consecutive updates maintain history
  Given path '/inventory/105'
  And header Authorization = adminToken
  And request { "stock": 100 }
  When method PUT
  Then status 200
  * def firstUpdate = response.timestamp
  And match response.stock == 100
  
  Given path '/inventory/105'
  And header Authorization = adminToken
  And request { "stock": 75 }
  When method PUT
  Then status 200
  And match response.stock == 75
  And match response.timestamp != firstUpdate