# orders.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-21T01:46:59.501Z
# Feature: Orders
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts
# Review scenarios before running against real API

Feature: RetailShop Orders API

  Background:
    * url 'https://api.retailshop.com/v1'
    * def authToken = 'Bearer test-token-12345'
    * def invalidToken = 'Bearer invalid-token-xyz'
    * def validOrderId = 12345
    * def nonexistentOrderId = 999999
    * def validOrderPayload = { "items": [{ "product_id": 101, "quantity": 2, "price": 29.99 }], "shipping_address": "123 Main St", "payment_method": "credit_card" }

  Scenario: Get all orders - Happy path with valid token
    Given path '/orders'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match response == '#array'
    And match each response contains { id: '#number', status: '#string' }

  Scenario: Get all orders - No authorization token returns 401
    Given path '/orders'
    When method GET
    Then status 401
    And match response.error == '#string'

  Scenario: Get all orders - Invalid authorization token returns 401
    Given path '/orders'
    And header Authorization = invalidToken
    When method GET
    Then status 401

  Scenario: Post new order - Happy path returns 201
    Given path '/orders'
    And header Authorization = authToken
    And request validOrderPayload
    When method POST
    Then status 201
    And match response.id == '#number'
    And match response.status == 'pending'
    * def createdOrderId = response.id

  Scenario: Post new order - No authorization token returns 401
    Given path '/orders'
    And request validOrderPayload
    When method POST
    Then status 401

  Scenario: Post new order - Invalid authorization token returns 401
    Given path '/orders'
    And header Authorization = invalidToken
    And request validOrderPayload
    When method POST
    Then status 401

  Scenario: Post new order - Invalid order data returns 400
    Given path '/orders'
    And header Authorization = authToken
    And request { "items": [], "shipping_address": "" }
    When method POST
    Then status 400
    And match response.errors == '#array'

  Scenario: Post new order - Non-numeric product ID returns 400
    Given path '/orders'
    And header Authorization = authToken
    And request { "items": [{ "product_id": "invalid", "quantity": 2 }], "shipping_address": "123 Main St", "payment_method": "credit_card" }
    When method POST
    Then status 400

  Scenario: Post new order - Negative quantity returns 400
    Given path '/orders'
    And header Authorization = authToken
    And request { "items": [{ "product_id": 101, "quantity": -1 }], "shipping_address": "123 Main St", "payment_method": "credit_card" }
    When method POST
    Then status 400

  Scenario: Post new order - Insufficient stock returns 422
    Given path '/orders'
    And header Authorization = authToken
    And request { "items": [{ "product_id": 999, "quantity": 10000 }], "shipping_address": "123 Main St", "payment_method": "credit_card" }
    When method POST
    Then status 422
    And match response.message contains 'stock'

  Scenario: Post new order - Invalid payment method returns 422
    Given path '/orders'
    And header Authorization = authToken
    And request { "items": [{ "product_id": 101, "quantity": 1 }], "shipping_address": "123 Main St", "payment_method": "invalid_payment" }
    When method POST
    Then status 422

  Scenario: Get order by ID - Happy path returns 200
    Given path '/orders/' + validOrderId
    And header Authorization = authToken
    When method GET
    Then status 200
    And match response.id == validOrderId
    And match response.status == '#string'
    And match response.items == '#array'

  Scenario: Get order by ID - No authorization token returns 401
    Given path '/orders/' + validOrderId
    When method GET
    Then status 401

  Scenario: Get order by ID - Invalid authorization token returns 401
    Given path '/orders/' + validOrderId
    And header Authorization = invalidToken
    When method GET
    Then status 401

  Scenario: Get order by ID - Non-numeric ID returns 404
    Given path '/orders/invalid-id'
    And header Authorization = authToken
    When method GET
    Then status 404

  Scenario: Get order by ID - Nonexistent order returns 404
    Given path '/orders/' + nonexistentOrderId
    And header Authorization = authToken
    When method GET
    Then status 404
    And match response.error == '#string'

  Scenario: Get order by ID - Access other user's order returns 403
    Given path '/orders/54321'
    And header Authorization = authToken
    When method GET
    Then status 403
    And match response.error contains 'not authorized'

  Scenario: Cancel order - Happy path returns 200
    Given path '/orders/' + validOrderId + '/cancel'
    And header Authorization = authToken
    When method PUT
    Then status 200
    And match response.status == 'cancelled'

  Scenario: Cancel order - No authorization token returns 401
    Given path '/orders/' + validOrderId + '/cancel'
    When method PUT
    Then status 401

  Scenario: Cancel order - Invalid authorization token returns 401
    Given path '/orders/' + validOrderId + '/cancel'
    And header Authorization = invalidToken
    When method PUT
    Then status 401

  Scenario: Cancel order - Non-numeric ID returns 404
    Given path '/orders/not-a-number/cancel'
    And header Authorization = authToken
    When method PUT
    Then status 404

  Scenario: Cancel order - Nonexistent order returns 404
    Given path '/orders/' + nonexistentOrderId + '/cancel'
    And header Authorization = authToken
    When method PUT
    Then status 404

  Scenario: Cancel order - Already shipped order returns 400
    Given path '/orders/67890/cancel'
    And header Authorization = authToken
    When method PUT
    Then status 400
    And match response.error contains 'already shipped'

  Scenario: Get order tracking - Happy path returns 200
    Given path '/orders/' + validOrderId + '/tracking'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match response.carrier == '#string'
    And match response.tracking_number == '#string'
    And match response.status == '#string'

  Scenario: Get order tracking - No authorization token returns 401
    Given path '/orders/' + validOrderId + '/tracking'
    When method GET
    Then status 401

  Scenario: Get order tracking - Invalid authorization token returns 401
    Given path '/orders/' + validOrderId + '/tracking'
    And header Authorization = invalidToken
    When method GET
    Then status 401

  Scenario: Get order tracking - Non-numeric ID returns 404
    Given path '/orders/abc123/tracking'
    And header Authorization = authToken
    When method GET
    Then status 404

  Scenario: Get order tracking - Nonexistent order returns 404
    Given path '/orders/' + nonexistentOrderId + '/tracking'
    And header Authorization = authToken
    When method GET
    Then status 404
    And match response.error == '#string'