# orders.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T03:38:54.673Z
# Feature: Orders
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Orders API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'

Scenario: Login and get auth token for reuse
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  * def userId = response.user._id

Scenario: Get real product ID for cart creation
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id

Scenario: Create cart with product for checkout testing
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 201
  * def cartId = response.data._id

Scenario: Happy path - Create checkout session with valid cart and shipping address
  # This test creates a real cart first, then creates a checkout session
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 201
  * def cartId = response.data._id
  Given path '/orders/checkout-session/' + cartId
  And header token = authToken
  And request { "shippingAddress": { "details": "123 Main St", "phone": "1234567890", "city": "Cairo", "postalCode": "12345" } }
  When method POST
  Then status 200
  And match response.session != null

Scenario: Create checkout session - Missing required shippingAddress field returns 400
  # This test validates that missing shippingAddress returns 400
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 201
  * def cartId = response.data._id
  Given path '/orders/checkout-session/' + cartId
  And header token = authToken
  And request {}
  When method POST
  Then status 400

Scenario: Create checkout session - No auth token returns 401
  # This test validates that requests without token header return 401
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 201
  * def cartId = response.data._id
  Given path '/orders/checkout-session/' + cartId
  And request { "shippingAddress": { "details": "123 Main St", "phone": "1234567890", "city": "Cairo", "postalCode": "12345" } }
  When method POST
  Then status 401

Scenario: Create checkout session - Invalid auth token returns 401
  # This test validates that requests with invalid token return 401
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 201
  * def cartId = response.data._id
  Given path '/orders/checkout-session/' + cartId
  And header token = 'invalid-token-xyz'
  And request { "shippingAddress": { "details": "123 Main St", "phone": "1234567890", "city": "Cairo", "postalCode": "12345" } }
  When method POST
  Then status 401

Scenario: Create checkout session - Non-existent cart returns 404
  # This test validates that non-existent cartId returns 404
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  * def nonExistentCartId = '000000000000000000000000'
  Given path '/orders/checkout-session/' + nonExistentCartId
  And header token = authToken
  And request { "shippingAddress": { "details": "123 Main St", "phone": "1234567890", "city": "Cairo", "postalCode": "12345" } }
  When method POST
  Then status 404

Scenario: Happy path - Get all orders for user returns 200 with orders array
  # This test retrieves all orders for the authenticated user
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  * def userId = response.user._id
  Given path '/orders/user/' + userId
  And header token = authToken
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get user orders - No auth token returns 401
  # This test validates that requests without token header return 401
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def userId = response.user._id
  Given path '/orders/user/' + userId
  When method GET
  Then status 401

Scenario: Get user orders - Invalid auth token returns 401
  # This test validates that requests with invalid token return 401
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def userId = response.user._id
  Given path '/orders/user/' + userId
  And header token = 'invalid-token-xyz'
  When method GET
  Then status 401

Scenario: Get user orders - Non-existent user returns 404
  # This test validates that non-existent userId returns 404
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  * def nonExistentUserId = '000000000000000000000000'
  Given path '/orders/user/' + nonExistentUserId
  And header token = authToken
  When method GET
  Then status 404