# orders.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T02:56:37.578Z
# Feature: Orders
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Orders API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'
  
  # Login to get auth token and userId
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  * def userId = response.user._id
  
  # Fetch a real product to add to cart
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id

Scenario: Create checkout session - Happy path with valid cart and shipping address
  # First, add a product to cart
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200 || status 201
  * def cartId = response.data._id
  
  # Now create checkout session with valid cart and shipping address
  Given path '/orders/checkout-session/' + cartId
  And header token = authToken
  And request { "shippingAddress": { "details": "123 Main St", "phone": "1234567890", "city": "Cairo", "postalCode": "12345" } }
  When method POST
  Then status 200
  And match response.status == 'success'
  And match response.session != null

Scenario: Create checkout session - Missing required shippingAddress field
  # Add product to cart first
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200 || status 201
  * def cartId = response.data._id
  
  # Attempt to create checkout without shippingAddress
  Given path '/orders/checkout-session/' + cartId
  And header token = authToken
  And request {}
  When method POST
  Then status 400
  And match response.message contains 'required'

Scenario: Create checkout session - Invalid cart ID format returns 500
  # Use invalid MongoDB ID format
  Given path '/orders/checkout-session/invalid-id'
  And header token = authToken
  And request { "shippingAddress": { "details": "123 Main St", "phone": "1234567890", "city": "Cairo", "postalCode": "12345" } }
  When method POST
  Then status 500

Scenario: Create checkout session - Non-existent cart ID returns 404
  # Use valid MongoDB ID format but non-existent
  Given path '/orders/checkout-session/000000000000000000000000'
  And header token = authToken
  And request { "shippingAddress": { "details": "123 Main St", "phone": "1234567890", "city": "Cairo", "postalCode": "12345" } }
  When method POST
  Then status 404
  And match response.message contains 'not found' || match response.message contains 'Cart'

Scenario: Create checkout session - Missing auth token returns 401
  # Add product to cart first
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200 || status 201
  * def cartId = response.data._id
  
  # Attempt without token
  Given path '/orders/checkout-session/' + cartId
  And request { "shippingAddress": { "details": "123 Main St", "phone": "1234567890", "city": "Cairo", "postalCode": "12345" } }
  When method POST
  Then status 401
  And match response.message contains 'Unauthorized' || match response.message contains 'authorize' || match response.message contains 'token'

Scenario: Create checkout session - Invalid auth token returns 401
  # Add product to cart first
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200 || status 201
  * def cartId = response.data._id
  
  # Attempt with invalid token
  Given path '/orders/checkout-session/' + cartId
  And header token = 'invalid-token-12345'
  And request { "shippingAddress": { "details": "123 Main St", "phone": "1234567890", "city": "Cairo", "postalCode": "12345" } }
  When method POST
  Then status 401
  And match response.message contains 'Unauthorized' || match response.message contains 'authorize' || match response.message contains 'token'

Scenario: Create checkout session - Invalid shippingAddress data type returns 400
  # Add product to cart first
  Given path '/cart'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200 || status 201
  * def cartId = response.data._id
  
  # Attempt with shippingAddress as string instead of object
  Given path '/orders/checkout-session/' + cartId
  And header token = authToken
  And request { "shippingAddress": "not-an-object" }
  When method POST
  Then status 400
  And match response.message contains 'invalid' || match response.message contains 'Invalid'

Scenario: Get user orders - Happy path returns user's orders
  # Fetch orders for authenticated user
  Given path '/orders/user/' + userId
  And header token = authToken
  When method GET
  Then status 200
  And match response.results == '#number'
  And match response.data == '#[]'

Scenario: Get user orders - Missing auth token returns 401
  # Attempt to get orders without token
  Given path '/orders/user/' + userId
  When method GET
  Then status 401
  And match response.message contains 'Unauthorized' || match response.message contains 'authorize' || match response.message contains 'token'

Scenario: Get user orders - Invalid auth token returns 401
  # Attempt with invalid token
  Given path '/orders/user/' + userId
  And header token = 'invalid-token-xyz'
  When method GET
  Then status 401
  And match response.message contains 'Unauthorized' || match response.message contains 'authorize' || match response.message contains 'token'

Scenario: Get user orders - Non-existent user ID returns 404
  # Use valid MongoDB ID format but non-existent user
  Given path '/orders/user/000000000000000000000000'
  And header token = authToken
  When method GET
  Then status 404
  And match response.message contains 'No orders' || match response.message contains 'not found'

Scenario: Get user orders - Invalid user ID format returns 500
  # Use invalid MongoDB ID format
  Given path '/orders/user/invalid-user-id'
  And header token = authToken
  When method GET
  Then status 500