# payments.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-21T01:47:17.856Z
# Feature: Payments
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts
# Review scenarios before running against real API

Feature: RetailShop Payments API

  Background:
    * url 'https://api.retailshop.com/v1'
    * def authToken = 'Bearer test-token-12345'
    * def invalidToken = 'Bearer invalid-token-xyz'

  # ===== GET /payments/methods - Happy Path and Auth =====

  Scenario: Get payment methods with valid authentication
    Given path '/payments/methods'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match response == '#array'
    And match each response contains { id: '#number', cardNumber: '#string', expiryDate: '#string' }

  Scenario: Get payment methods without authentication token
    Given path '/payments/methods'
    When method GET
    Then status 401
    And match response.error == '#string'

  Scenario: Get payment methods with invalid authentication token
    Given path '/payments/methods'
    And header Authorization = invalidToken
    When method GET
    Then status 401

  # ===== POST /payments/methods - Happy Path and Auth =====

  Scenario: Add new payment method with valid data
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": "4532123456789010", "expiryDate": "12/25", "cvv": "123" }
    When method POST
    Then status 201
    And match response.id == '#number'
    And match response.cardNumber == '4532123456789010'
    And match response.expiryDate == '12/25'

  Scenario: Add payment method without authentication token
    Given path '/payments/methods'
    And request { "cardNumber": "4532123456789010", "expiryDate": "12/25", "cvv": "123" }
    When method POST
    Then status 401

  Scenario: Add payment method with invalid authentication token
    Given path '/payments/methods'
    And header Authorization = invalidToken
    And request { "cardNumber": "4532123456789010", "expiryDate": "12/25", "cvv": "123" }
    When method POST
    Then status 401

  Scenario: Add payment method with missing cardNumber
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "expiryDate": "12/25", "cvv": "123" }
    When method POST
    Then status 400
    And match response.error contains 'cardNumber'

  Scenario: Add payment method with missing expiryDate
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": "4532123456789010", "cvv": "123" }
    When method POST
    Then status 400
    And match response.error contains 'expiryDate'

  Scenario: Add payment method with missing cvv
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": "4532123456789010", "expiryDate": "12/25" }
    When method POST
    Then status 400
    And match response.error contains 'cvv'

  Scenario: Add payment method with invalid cardNumber format
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": "invalid", "expiryDate": "12/25", "cvv": "123" }
    When method POST
    Then status 400
    And match response.error contains 'cardNumber'

  Scenario: Add payment method with invalid expiryDate format
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": "4532123456789010", "expiryDate": "invalid", "cvv": "123" }
    When method POST
    Then status 400
    And match response.error contains 'expiryDate'

  Scenario: Add payment method with invalid cvv format
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": "4532123456789010", "expiryDate": "12/25", "cvv": "ab" }
    When method POST
    Then status 400
    And match response.error contains 'cvv'

  Scenario: Add payment method with numeric cardNumber type instead of string
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": 4532123456789010, "expiryDate": "12/25", "cvv": "123" }
    When method POST
    Then status 400

  Scenario: Add payment method with card declined
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": "5555555555554444", "expiryDate": "12/25", "cvv": "123" }
    When method POST
    Then status 422
    And match response.error == 'Card declined'

  # ===== DELETE /payments/methods/{id} - Happy Path and Auth =====

  Scenario: Delete payment method with valid id
    Given path '/payments/methods/42'
    And header Authorization = authToken
    When method DELETE
    Then status 200
    And match response.message contains 'removed'

  Scenario: Delete payment method without authentication token
    Given path '/payments/methods/42'
    When method DELETE
    Then status 401

  Scenario: Delete payment method with invalid authentication token
    Given path '/payments/methods/42'
    And header Authorization = invalidToken
    When method DELETE
    Then status 401

  Scenario: Delete payment method with non-existent id
    Given path '/payments/methods/999999'
    And header Authorization = authToken
    When method DELETE
    Then status 404
    And match response.error == 'Payment method not found'

  Scenario: Delete payment method with invalid non-numeric id
    Given path '/payments/methods/abc'
    And header Authorization = authToken
    When method DELETE
    Then status 400
    And match response.error contains 'id'

  Scenario: Delete payment method with negative id
    Given path '/payments/methods/-1'
    And header Authorization = authToken
    When method DELETE
    Then status 404

  Scenario: Delete payment method with id zero
    Given path '/payments/methods/0'
    And header Authorization = authToken
    When method DELETE
    Then status 404

  # ===== Boundary Value Tests =====

  Scenario: Add payment method with boundary length cardNumber
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": "4532123456789010", "expiryDate": "01/99", "cvv": "999" }
    When method POST
    Then status 201
    And match response.cardNumber == '4532123456789010'

  Scenario: Add payment method with empty string cardNumber
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": "", "expiryDate": "12/25", "cvv": "123" }
    When method POST
    Then status 400

  Scenario: Add payment method with empty string expiryDate
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": "4532123456789010", "expiryDate": "", "cvv": "123" }
    When method POST
    Then status 400

  Scenario: Add payment method with empty string cvv
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": "4532123456789010", "expiryDate": "12/25", "cvv": "" }
    When method POST
    Then status 400

  Scenario: Add payment method with expired date
    Given path '/payments/methods'
    And header Authorization = authToken
    And request { "cardNumber": "4532123456789010", "expiryDate": "01/20", "cvv": "123" }
    When method POST
    Then status 400
    And match response.error contains 'expired'

  Scenario: Delete payment method with very large id
    Given path '/payments/methods/9999999999'
    And header Authorization = authToken
    When method DELETE
    Then status 404