# products.feature - AUTO-GENERATED by karate-generator.py (Python + Groq FREE)
# Generated: 2026-05-22T08:58:35.454337
# Feature: Products
# API: https://ecommerce.routemisr.com/api/v1
# Uses REAL API discovery - status codes verified against live API

Feature: RetailShop Products API
Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  * def userId = response.user._id

Scenario: Happy Path Get all products
  Given header token = authToken
  When method GET
  Then status 200

Scenario: Happy Path Get product by ID
  Given path '/products/' + '6428ebc6dc1175abc65ca0b9'
  When method GET
  Then status 200

Scenario: 401 - No auth token Get all products
  When method GET
  Then status 401
  And match response == {"error": "You are not logged in. Please login to get access"}

Scenario: 401 - Invalid auth token Get all products
  And header token = 'invalid-token-xyz'
  When method GET
  Then status 401
  And match response == {"error": "You are not logged in. Please login to get access"}

Scenario: 400 - Missing ID Get product
  Given path '/products/'
  When method GET
  Then status 400

Scenario: 404 - Not found Get product
  Given path '/products/000000000000000000000000'
  When method GET
  Then status 404

Scenario: 400 - Invalid ID Get product
  Given path '/products/invalid-id'
  When method GET
  Then status 400

Scenario: 401 - No auth token Get product by ID
  Given path '/products/' + '6428ebc6dc1175abc65ca0b9'
  When method GET
  Then status 200

Scenario: 401 - Invalid auth token Get product by ID
  Given path '/products/' + '6428ebc6dc1175abc65ca0b9'
  And header token = 'invalid-token-xyz'
  When method GET
  Then status 401
  And match response == {"error": "You are not logged in. Please login to get access"}