# products.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T02:55:58.476Z
# Feature: Products
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Products API

  Background:
    * url 'https://ecommerce.routemisr.com/api/v1'
    * def testEmail = 'qelead.test2026@gmail.com'
    * def testPassword = 'QeTest@2026'

  # ============================================================================
  # GET /products - List all products with optional filters
  # ============================================================================

  Scenario: Get all products - happy path returns 200 with product list
    # Verify the endpoint returns a list of all products
    Given path '/products'
    When method GET
    Then status 200
    And match response.data == '#[]'
    And match response.data[0].id == '#string'
    And match response.data[0].title == '#string'

  Scenario: Get products with page parameter - pagination works correctly
    # Verify pagination with valid page number
    Given path '/products'
    And param page = 1
    When method GET
    Then status 200
    And match response.data == '#[]'

  Scenario: Get products with limit parameter - limits results correctly
    # Verify limit parameter restricts number of results
    Given path '/products'
    And param limit = 5
    When method GET
    Then status 200
    And match response.data == '#[]'

  Scenario: Get products with sort parameter - sorting works correctly
    # Verify sort parameter orders results
    Given path '/products'
    And param sort = 'name'
    When method GET
    Then status 200
    And match response.data == '#[]'

  Scenario: Get products with keyword parameter - search works correctly
    # Verify keyword search filters products
    Given path '/products'
    And param keyword = 'phone'
    When method GET
    Then status 200
    And match response.data == '#[]'

  Scenario: Get products with multiple filter parameters - combined filters work
    # Verify multiple parameters can be combined
    Given path '/products'
    And param page = 1
    And param limit = 10
    And param sort = 'price'
    And param keyword = 'laptop'
    When method GET
    Then status 200
    And match response.data == '#[]'

  # ============================================================================
  # GET /products/{id} - Get single product by MongoDB ID
  # ============================================================================

  Scenario: Get product by valid ID - happy path returns 200 with product details
    # First fetch a real product ID, then retrieve its details
    Given path '/products'
    And param limit = 1
    When method GET
    Then status 200
    * def productId = response.data[0].id
    
    # Now get the product by ID
    Given path '/products/' + productId
    When method GET
    Then status 200
    And match response.data.id == '#string'
    And match response.data.title == '#string'
    And match response.data.description == '#string'
    And match response.data.price == '#number'

  Scenario: Get product by non-existent valid MongoDB ID format - returns 404
    # Test with a valid MongoDB ID format that doesn't exist
    Given path '/products/000000000000000000000000'
    When method GET
    Then status 404

  Scenario: Get product by invalid MongoDB ID format - returns 500
    # Invalid ObjectId format triggers 500
    Given path '/products/invalid-id-format'
    When method GET
    Then status 500

  Scenario: Get product by empty ID path - invalid format returns 500
    # Missing ID parameter should fail
    Given path '/products/'
    When method GET
    Then status 404

  # ============================================================================
  # Authentication Tests - Products endpoint does NOT require auth
  # These tests verify the endpoint works without authentication
  # ============================================================================

  Scenario: Get products without any authentication - public endpoint works
    # Products endpoint is public, should work without token
    Given path '/products'
    And param limit = 1
    When method GET
    Then status 200
    And match response.data == '#[]'

  Scenario: Get single product without authentication - public endpoint works
    # Get a real product first
    Given path '/products'
    And param limit = 1
    When method GET
    Then status 200
    * def productId = response.data[0].id
    
    # Access without token should still work
    Given path '/products/' + productId
    When method GET
    Then status 200
    And match response.data.id == '#string'

  # ============================================================================
  # Edge Cases and Validation Tests
  # ============================================================================

  Scenario: Get products with numeric page parameter - valid pagination
    # Verify page parameter accepts positive integers
    Given path '/products'
    And param page = 2
    When method GET
    Then status 200
    And match response.data == '#[]'

  Scenario: Get products with numeric limit parameter - valid limit
    # Verify limit parameter accepts positive integers
    Given path '/products'
    And param limit = 20
    When method GET
    Then status 200
    And match response.data == '#[]'

  Scenario: Get products with string sort parameter - sorting supported
    # Verify sort accepts string values
    Given path '/products'
    And param sort = '-price'
    When method GET
    Then status 200
    And match response.data == '#[]'

  Scenario: Get products with special characters in keyword - search handles special chars
    # Verify keyword parameter handles special characters
    Given path '/products'
    And param keyword = 'test&special'
    When method GET
    Then status 200
    And match response.data == '#[]'