# products.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-21T13:27:49.244Z
# Feature: Products
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Products API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'
  * def validProductId = '507f1f77bcf86cd799439011'
  * def nonExistentProductId = '507f1f77bcf86cd799439099'
  * def invalidProductId = '000000000000000000000000'
  * def malformedProductId = 'not-a-valid-id'

Scenario: Get all products - Happy path returns 200 with product list
  Given path '/products'
  When method GET
  Then status 200
  And match response.data == '#[]'
  And match response.results == '#number'
  And match response.paginationResult.currentPage == '#number'

Scenario: Get all products with pagination - page parameter
  Given path '/products'
  And param page = 1
  When method GET
  Then status 200
  And match response.data == '#[]'
  And match response.paginationResult.currentPage == 1

Scenario: Get all products with limit parameter
  Given path '/products'
  And param limit = 10
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get all products with sort parameter - ascending
  Given path '/products'
  And param sort = 'price'
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get all products with sort parameter - descending
  Given path '/products'
  And param sort = '-price'
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get all products with keyword search filter
  Given path '/products'
  And param keyword = 'electronics'
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get all products with multiple filters combined
  Given path '/products'
  And param page = 1
  And param limit = 5
  And param sort = '-createdAt'
  And param keyword = 'laptop'
  When method GET
  Then status 200
  And match response.data == '#[]'
  And match response.paginationResult.limit == 5

Scenario: Get all products with invalid page parameter - negative number
  Given path '/products'
  And param page = -1
  When method GET
  Then status 400
  And match response.message contains 'Invalid'

Scenario: Get all products with invalid limit parameter - zero
  Given path '/products'
  And param limit = 0
  When method GET
  Then status 400
  And match response.message contains 'Invalid'

Scenario: Get all products with invalid limit parameter - very large number
  Given path '/products'
  And param limit = 999999999
  When method GET
  Then status 400
  And match response.message contains 'Invalid'

Scenario: Get all products with invalid sort parameter
  Given path '/products'
  And param sort = '!@#$%^'
  When method GET
  Then status 400

Scenario: Get all products with empty keyword parameter
  Given path '/products'
  And param keyword = ''
  When method GET
  Then status 200

Scenario: Get all products with very long keyword parameter
  Given path '/products'
  And param keyword = 'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz'
  When method GET
  Then status 200

Scenario: Get product by ID - Happy path returns 200 with product details
  Given path '/products/' + validProductId
  When method GET
  Then status 200
  And match response.data._id exists
  And match response.data.title == '#string'
  And match response.data.price == '#number'
  And match response.data.description == '#string'

Scenario: Get product by ID - Product not found returns 404
  Given path '/products/' + nonExistentProductId
  When method GET
  Then status 404
  And match response.message contains 'not found'

Scenario: Get product by ID - Invalid MongoDB ID format returns 400
  Given path '/products/' + invalidProductId
  When method GET
  Then status 400

Scenario: Get product by ID - Malformed ID string returns 400
  Given path '/products/' + malformedProductId
  When method GET
  Then status 400
  And match response.message contains 'Invalid'

Scenario: Get product by ID - Empty ID parameter returns 404
  Given path '/products/'
  When method GET
  Then status 404

Scenario: Get product by ID - ID with leading whitespace
  * def idWithSpace = ' ' + validProductId
  Given path '/products/' + idWithSpace
  When method GET
  Then status 400

Scenario: Get product by ID - ID with trailing whitespace
  * def idWithSpace = validProductId + ' '
  Given path '/products/' + idWithSpace
  When method GET
  Then status 400

Scenario: Get product by ID - ID with mixed case hex characters
  * def mixedCaseId = '507F1F77BCF86CD799439011'
  Given path '/products/' + mixedCaseId
  When method GET
  Then status 200

Scenario: Get product by ID - Very long ID parameter returns 400
  * def longId = '507f1f77bcf86cd799439011507f1f77bcf86cd799439011'
  Given path '/products/' + longId
  When method GET
  Then status 400

Scenario: Get product by ID - ID with special characters returns 400
  * def specialCharId = '507f1f77bcf86cd79943901!'
  Given path '/products/' + specialCharId
  When method GET
  Then status 400

Scenario: Get product by ID - Numeric ID string returns 400
  Given path '/products/123456789012345678901234'
  When method GET
  Then status 400

Scenario: Get product by ID - UUID format instead of MongoDB ID returns 400
  Given path '/products/550e8400-e29b-41d4-a716-446655440000'
  When method GET
  Then status 400

Scenario: Verify product response structure contains all required fields
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  And match response.data[0]._id == '#string'
  And match response.data[0].title == '#string'
  And match response.data[0].price == '#number'
  And match response.data[0].description == '#string'
  And match response.data[0].category exists
  And match response.data[0].image exists

Scenario: Get products - Verify pagination metadata structure
  Given path '/products'
  And param page = 1
  And param limit = 5
  When method GET
  Then status 200
  And match response.paginationResult.currentPage == '#number'
  And match response.paginationResult.limit == '#number'
  And match response.paginationResult.numberOfPages == '#number'
  And match response.results == '#number'

Scenario: Get products - Page parameter boundary - page 1 returns success
  Given path '/products'
  And param page = 1
  When method GET
  Then status 200
  And match response.paginationResult.currentPage == 1

Scenario: Get products - Limit parameter boundary - limit 1 returns success
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  And match response.paginationResult.limit == 1

Scenario: Get products - Verify all products in response have valid structure
  Given path '/products'
  And param limit = 3
  When method GET
  Then status 200
  And match response.data == '#[]'
  And match each response.data { _id: '#string', title: '#string', price: '#number' }

Scenario: Get product by valid ID - Verify product has ratings if available
  Given path '/products/' + validProductId
  When method GET
  Then status 200
  And match response.data._id == validProductId
  And match response.data.price == '#number'
  And response.data.price > 0

Scenario: Get products with string page parameter - returns 400
  Given path '/products'
  And param page = 'invalid'
  When method GET
  Then status 400

Scenario: Get products with string limit parameter - returns 400
  Given path '/products'
  And param limit = 'invalid'
  When method GET
  Then status 400

Scenario: Get products with decimal page parameter - returns 400
  Given path '/products'
  And param page = 1.5
  When method GET
  Then status 400

Scenario: Get products with decimal limit parameter - returns 400
  Given path '/products'
  And param limit = 10.7
  When method GET
  Then status 400

Scenario: Get product by ID multiple times - Verify consistent response
  Given path '/products/' + validProductId
  When method GET
  Then status 200
  * def firstResponse = response
  Given path '/products/' + validProductId
  When method GET
  Then status 200
  And match response.data._id == firstResponse.data._id
  And match response.data.title == firstResponse.data.title

Scenario: Get products - Verify no auth required for public endpoint
  Given path '/products'
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get product by ID - Verify no auth required for public endpoint
  Given path '/products/' + validProductId
  When method GET
  Then status 200
  And match response.data._id exists