# recommendations.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-21T01:47:36.367Z
# Feature: Recommendations
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts
# Review scenarios before running against real API

Feature: RetailShop Recommendations API

Background:
  * url 'https://api.retailshop.com/v1'
  * def authToken = 'Bearer test-token-12345'
  * def invalidToken = 'Bearer invalid-token-xyz'

Scenario: Get recommendations with valid authentication
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response == '#object'
  And match response.recommendations == '#array'
  And match each response.recommendations contains { id: '#number', productName: '#string', price: '#number' }

Scenario: Get recommendations returns valid response structure
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response.recommendations[0].id != null
  And match response.recommendations[0].productName != null
  And match response.recommendations[0].price != null
  And match response.recommendations[0].price == '#number'

Scenario: Get recommendations with empty result set
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response.recommendations == '[]'

Scenario: Unauthorized - missing authentication token
  Given path '/recommendations'
  When method GET
  Then status 401
  And match response.error == 'Unauthorized'
  And match response.message == '#string'

Scenario: Unauthorized - invalid token format
  Given path '/recommendations'
  And header Authorization = invalidToken
  When method GET
  Then status 401
  And match response.error == 'Unauthorized'

Scenario: Unauthorized - malformed bearer token
  Given path '/recommendations'
  And header Authorization = 'Bearer'
  When method GET
  Then status 401

Scenario: Unauthorized - missing Bearer prefix
  Given path '/recommendations'
  And header Authorization = 'test-token-12345'
  When method GET
  Then status 401

Scenario: Unauthorized - empty token value
  Given path '/recommendations'
  And header Authorization = 'Bearer '
  When method GET
  Then status 401

Scenario: Unauthorized - token with special characters
  Given path '/recommendations'
  And header Authorization = 'Bearer @#$%^&*()'
  When method GET
  Then status 401

Scenario: Get recommendations with valid token and custom headers
  Given path '/recommendations'
  And header Authorization = authToken
  And header Accept = 'application/json'
  And header Content-Type = 'application/json'
  When method GET
  Then status 200
  And match response.recommendations == '#array'

Scenario: Get recommendations response includes product details
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response.recommendations[0] contains { id: '#number', productName: '#string', description: '#string', price: '#number', category: '#string', inStock: '#boolean' }

Scenario: Get recommendations response includes discount information
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response.recommendations[0].discount == '#number || null'
  And match response.recommendations[0].discountedPrice == '#number || null'

Scenario: Get recommendations response includes recommendation reason
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response.recommendations[0].reason == '#string'

Scenario: Recommendation reason contains valid values
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  * def reasons = ['trending', 'personalized', 'similar_items', 'frequently_bought_together', 'new_arrival']
  And match response.recommendations[0].reason == '#? reasons.includes(_)'

Scenario: Product prices are positive numbers
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match each response.recommendations[*].price == '#number'
  * def prices = response.recommendations[*].price
  * def allPositive = prices.every(p => p > 0)
  And assert allPositive == true

Scenario: Product IDs are unique
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  * def ids = response.recommendations[*].id
  * def uniqueIds = [...new Set(ids)]
  And assert ids.length == uniqueIds.length

Scenario: Response contains pagination information
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response contains { totalCount: '#number', pageSize: '#number' }
  And match response.totalCount >= 0
  And match response.pageSize >= 0

Scenario: Response includes metadata
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response contains { timestamp: '#string', version: '#string' }

Scenario: Timestamp is valid ISO format
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  * def timestamp = response.timestamp
  * def isoRegex = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/
  And assert isoRegex.test(timestamp) == true

Scenario: Category field is valid
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  * def validCategories = ['electronics', 'clothing', 'home', 'sports', 'beauty', 'books']
  And match each response.recommendations[*].category == '#? validCategories.includes(_)'

Scenario: Stock status is boolean
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match each response.recommendations[*].inStock == '#boolean'

Scenario: Discount is null or valid percentage
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  * def discounts = response.recommendations[*].discount
  * def validDiscounts = discounts.every(d => d === null || (typeof d === 'number' && d >= 0 && d <= 100))
  And assert validDiscounts == true

Scenario: Rating field when present is valid
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  * def hasRating = response.recommendations[0].rating != null
  * if (hasRating) { assert response.recommendations[0].rating >= 0 && response.recommendations[0].rating <= 5 }

Scenario: Response has correct content type
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match responseHeaders['content-type'] == '#regex .*application/json.*'

Scenario: Response headers include caching information
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match responseHeaders['cache-control'] == '#string'

Scenario: Response includes API version
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match responseHeaders['x-api-version'] == '#string || null'

Scenario: Multiple requests return consistent structure
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  * def firstResponse = response
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response == '#object'
  And match response.recommendations == '#array'

Scenario: Null values handled correctly
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  * def hasNullDescription = response.recommendations.some(r => r.description === null)
  And match response.recommendations[0].id != null
  And match response.recommendations[0].productName != null

Scenario: Request with case-sensitive authorization header
  Given path '/recommendations'
  And header authorization = authToken
  When method GET
  Then status 200

Scenario: Request accepts multiple content types
  Given path '/recommendations'
  And header Authorization = authToken
  And header Accept = 'application/json, text/plain'
  When method GET
  Then status 200

Scenario: Response payload size is reasonable
  Given path '/recommendations'
  And header Authorization = authToken
  When method GET
  Then status 200
  * def responseString = JSON.stringify(response)
  * def payloadSize = responseString.length
  And assert payloadSize > 0 && payloadSize < 1000000