# users.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-21T01:47:08.521Z
# Feature: Users
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts
# Review scenarios before running against real API

Feature: RetailShop Users API

Background:
    * url 'https://api.retailshop.com/v1'
    * def authToken = 'Bearer test-token-12345'
    * def invalidToken = 'Bearer invalid-token-xyz'

Scenario: Get current user profile - happy path with valid auth
    Given path '/users/me'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match response.id == '#number'
    And match response.email == '#string'
    And match response.firstName == '#string'
    And match response.lastName == '#string'

Scenario: Get current user profile - missing authorization header
    Given path '/users/me'
    When method GET
    Then status 401
    And match response.error == '#string'

Scenario: Get current user profile - invalid authorization token
    Given path '/users/me'
    And header Authorization = invalidToken
    When method GET
    Then status 401
    And match response.error == '#string'

Scenario: Update user profile - happy path with valid data
    Given path '/users/me'
    And header Authorization = authToken
    And request { firstName: 'John', lastName: 'Doe', phone: '555-1234' }
    When method PUT
    Then status 200
    And match response.firstName == 'John'
    And match response.lastName == 'Doe'
    And match response.phone == '555-1234'

Scenario: Update user profile - missing authorization header
    Given path '/users/me'
    And request { firstName: 'Jane' }
    When method PUT
    Then status 401

Scenario: Update user profile - invalid authorization token
    Given path '/users/me'
    And header Authorization = invalidToken
    And request { firstName: 'Jane' }
    When method PUT
    Then status 401

Scenario: Update user profile - invalid data type for firstName
    Given path '/users/me'
    And header Authorization = authToken
    And request { firstName: 12345, lastName: 'Doe' }
    When method PUT
    Then status 400
    And match response.error == '#string'

Scenario: Update user profile - invalid email format
    Given path '/users/me'
    And header Authorization = authToken
    And request { email: 'not-an-email' }
    When method PUT
    Then status 400
    And match response.message contains 'email'

Scenario: Update user profile - empty request body
    Given path '/users/me'
    And header Authorization = authToken
    And request {}
    When method PUT
    Then status 200

Scenario: Update user profile - null value for firstName
    Given path '/users/me'
    And header Authorization = authToken
    And request { firstName: null }
    When method PUT
    Then status 400

Scenario: Delete current user account - happy path
    Given path '/users/me'
    And header Authorization = authToken
    When method DELETE
    Then status 200
    And match response.message contains 'deleted'

Scenario: Delete user account - missing authorization header
    Given path '/users/me'
    When method DELETE
    Then status 401
    And match response.error == '#string'

Scenario: Delete user account - invalid authorization token
    Given path '/users/me'
    And header Authorization = invalidToken
    When method DELETE
    Then status 401

Scenario: Change password - happy path with valid credentials
    Given path '/users/me/password'
    And header Authorization = authToken
    And request { currentPassword: 'OldPassword123!', newPassword: 'NewPassword456!' }
    When method PUT
    Then status 200
    And match response.message contains 'password'

Scenario: Change password - missing authorization header
    Given path '/users/me/password'
    And request { currentPassword: 'OldPassword123!', newPassword: 'NewPassword456!' }
    When method PUT
    Then status 401

Scenario: Change password - invalid authorization token
    Given path '/users/me/password'
    And header Authorization = invalidToken
    And request { currentPassword: 'OldPassword123!', newPassword: 'NewPassword456!' }
    When method PUT
    Then status 401

Scenario: Change password - missing currentPassword field
    Given path '/users/me/password'
    And header Authorization = authToken
    And request { newPassword: 'NewPassword456!' }
    When method PUT
    Then status 400
    And match response.error contains 'currentPassword'

Scenario: Change password - missing newPassword field
    Given path '/users/me/password'
    And header Authorization = authToken
    And request { currentPassword: 'OldPassword123!' }
    When method PUT
    Then status 400
    And match response.error contains 'newPassword'

Scenario: Change password - missing both required fields
    Given path '/users/me/password'
    And header Authorization = authToken
    And request {}
    When method PUT
    Then status 400

Scenario: Change password - invalid password format for newPassword
    Given path '/users/me/password'
    And header Authorization = authToken
    And request { currentPassword: 'OldPassword123!', newPassword: 'weak' }
    When method PUT
    Then status 400
    And match response.message contains 'password'

Scenario: Change password - currentPassword incorrect
    Given path '/users/me/password'
    And header Authorization = authToken
    And request { currentPassword: 'WrongPassword123!', newPassword: 'NewPassword456!' }
    When method PUT
    Then status 401
    And match response.message contains 'incorrect'

Scenario: Change password - newPassword same as currentPassword
    Given path '/users/me/password'
    And header Authorization = authToken
    And request { currentPassword: 'SamePassword123!', newPassword: 'SamePassword123!' }
    When method PUT
    Then status 400

Scenario: Change password - newPassword is empty string
    Given path '/users/me/password'
    And header Authorization = authToken
    And request { currentPassword: 'OldPassword123!', newPassword: '' }
    When method PUT
    Then status 400

Scenario: Change password - currentPassword is null
    Given path '/users/me/password'
    And header Authorization = authToken
    And request { currentPassword: null, newPassword: 'NewPassword456!' }
    When method PUT
    Then status 400

Scenario: Change password - invalid data type for currentPassword
    Given path '/users/me/password'
    And header Authorization = authToken
    And request { currentPassword: 12345, newPassword: 'NewPassword456!' }
    When method PUT
    Then status 400

Scenario: Update profile - boundary test with very long firstName
    Given path '/users/me'
    And header Authorization = authToken
    And request { firstName: '#(karate.repeat("a", 256))' }
    When method PUT
    Then status 400

Scenario: Update profile - boundary test with special characters in firstName
    Given path '/users/me'
    And header Authorization = authToken
    And request { firstName: '<script>alert("xss")</script>' }
    When method PUT
    Then status 400

Scenario: Update profile - valid special characters in lastName
    Given path '/users/me'
    And header Authorization = authToken
    And request { lastName: "O'Brien-Smith" }
    When method PUT
    Then status 200
    And match response.lastName == "O'Brien-Smith"