# wishlist.feature - AUTO-GENERATED by karate-generator.py (Python + Groq FREE)
# Generated: 2026-05-22T08:59:31.444351
# Feature: Wishlist
# API: https://ecommerce.routemisr.com/api/v1
# Uses REAL API discovery - status codes verified against live API

Feature: RetailShop Wishlist API
Background:
    * url 'https://ecommerce.routemisr.com/api/v1'
    * def testEmail = 'qelead.test2026@gmail.com'
    * def testPassword = 'QeTest@2026'
    Given path '/auth/signin'
    And request { "email": "#(testEmail)", "password": "#(testPassword)" }
    When method POST
    Then status 200
    * def authToken = response.token
    * def userId = response.user._id
    * url 'https://ecommerce.routemisr.com/api/v1'

Scenario: Happy Path Get Wishlist
    Given path '/wishlist'
    And header token = authToken
    When method GET
    Then status 200

Scenario: Happy Path Add to Wishlist
    Given path '/wishlist'
    And header token = authToken
    And request { "productId": "6428ebc6dc1175abc65ca0b9" }
    When method POST
    Then status 200

Scenario: Happy Path Remove from Wishlist
    Given path '/wishlist/6428ebc6dc1175abc65ca0b9'
    And header token = authToken
    When method DELETE
    Then status 200

Scenario: No Auth Token Get Wishlist
    Given path '/wishlist'
    When method GET
    Then status 401
    And match response == { message: "You are not logged in. Please login to get access" }

Scenario: No Auth Token Add to Wishlist
    Given path '/wishlist'
    And request { "productId": "6428ebc6dc1175abc65ca0b9" }
    When method POST
    Then status 401
    And match response == { message: "You are not logged in. Please login to get access" }

Scenario: No Auth Token Remove from Wishlist
    Given path '/wishlist/6428ebc6dc1175abc65ca0b9'
    When method DELETE
    Then status 401
    And match response == { message: "You are not logged in. Please login to get access" }

Scenario: Invalid Auth Token Get Wishlist
    Given path '/wishlist'
    And header token = 'invalid-token-xyz'
    When method GET
    Then status 401

Scenario: Invalid Auth Token Add to Wishlist
    Given path '/wishlist'
    And header token = 'invalid-token-xyz'
    And request { "productId": "6428ebc6dc1175abc65ca0b9" }
    When method POST
    Then status 401

Scenario: Invalid Auth Token Remove from Wishlist
    Given path '/wishlist/6428ebc6dc1175abc65ca0b9'
    And header token = 'invalid-token-xyz'
    When method DELETE
    Then status 401

Scenario: Missing Required Fields Add to Wishlist
    Given path '/wishlist'
    And header token = authToken
    And request {}
    When method POST
    Then status 400

Scenario: Not Found Remove from Wishlist
    Given path '/wishlist/000000000000000000000000'
    And header token = authToken
    When method DELETE
    Then status 404