# wishlist.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T03:39:00.694Z
# Feature: Wishlist
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Wishlist API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'

Scenario: Get wishlist with valid auth token - Happy Path
  # Test retrieving user's wishlist successfully with authentication
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/wishlist'
  And header token = authToken
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Add product to wishlist - Happy Path
  # Test adding a real product to wishlist successfully
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/wishlist'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200

Scenario: Remove product from wishlist - Happy Path
  # Test removing a product from wishlist successfully
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/wishlist'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  Given path '/wishlist/' + productId
  And header token = authToken
  When method DELETE
  Then status 200

Scenario: Get wishlist without auth token - 401 Unauthorized
  # Test getting wishlist fails when no token header is provided
  Given path '/wishlist'
  When method GET
  Then status 401

Scenario: Add product to wishlist without auth token - 401 Unauthorized
  # Test adding to wishlist fails when no token header is provided
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/wishlist'
  And request { "productId": "#(productId)" }
  When method POST
  Then status 401

Scenario: Remove product from wishlist without auth token - 401 Unauthorized
  # Test removing from wishlist fails when no token header is provided
  Given path '/wishlist/000000000000000000000000'
  When method DELETE
  Then status 401

Scenario: Get wishlist with invalid auth token - 401 Unauthorized
  # Test getting wishlist fails with invalid token
  Given path '/wishlist'
  And header token = 'invalid-token-xyz'
  When method GET
  Then status 401

Scenario: Add product to wishlist with invalid auth token - 401 Unauthorized
  # Test adding to wishlist fails with invalid token
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id
  Given path '/wishlist'
  And header token = 'invalid-token-xyz'
  And request { "productId": "#(productId)" }
  When method POST
  Then status 401

Scenario: Remove product from wishlist with invalid auth token - 401 Unauthorized
  # Test removing from wishlist fails with invalid token
  Given path '/wishlist/000000000000000000000000'
  And header token = 'invalid-token-xyz'
  When method DELETE
  Then status 401

Scenario: Add product to wishlist with missing productId - 400 Bad Request
  # Test adding to wishlist fails when required productId field is omitted
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/wishlist'
  And header token = authToken
  And request {}
  When method POST
  Then status 400

Scenario: Remove non-existent product from wishlist - 404 Not Found
  # Test removing a product that is not in wishlist returns 404
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  Given path '/wishlist/000000000000000000000000'
  And header token = authToken
  When method DELETE
  Then status 404