# wishlist.feature - AUTO-GENERATED by karate-generator.ts
# Generated: 2026-05-22T02:56:44.260Z
# Feature: Wishlist
# API: https://ecommerce.routemisr.com/api/v1
# DO NOT EDIT - regenerate using: npx tsx ai-modules/module1-api/karate-generator.ts

Feature: RetailShop Wishlist API

Background:
  * url 'https://ecommerce.routemisr.com/api/v1'
  * def testEmail = 'qelead.test2026@gmail.com'
  * def testPassword = 'QeTest@2026'
  # Login to get auth token
  Given path '/auth/signin'
  And request { "email": "#(testEmail)", "password": "#(testPassword)" }
  When method POST
  Then status 200
  * def authToken = response.token
  * def userId = response.user._id
  # Fetch a real product ID for testing
  Given path '/products'
  And param limit = 1
  When method GET
  Then status 200
  * def productId = response.data[0]._id

Scenario: Get wishlist - happy path with valid token
  # Verify user can retrieve their wishlist when authenticated
  Given path '/wishlist'
  And header token = authToken
  When method GET
  Then status 200
  And match response.data == '#[]'

Scenario: Get wishlist - without authentication token
  # Verify 401 when accessing wishlist without token
  Given path '/wishlist'
  When method GET
  Then status 401

Scenario: Get wishlist - with invalid token
  # Verify 401 when accessing wishlist with malformed token
  Given path '/wishlist'
  And header token = 'invalid-token'
  When method GET
  Then status 401

Scenario: Add product to wishlist - happy path
  # Verify product can be added to wishlist successfully
  Given path '/wishlist'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  And match response.message == '#string'

Scenario: Add product to wishlist - without authentication token
  # Verify 401 when adding to wishlist without token
  Given path '/wishlist'
  And request { "productId": "#(productId)" }
  When method POST
  Then status 401

Scenario: Add product to wishlist - with invalid token
  # Verify 401 when adding to wishlist with malformed token
  Given path '/wishlist'
  And header token = 'invalid-token'
  And request { "productId": "#(productId)" }
  When method POST
  Then status 401

Scenario: Add product to wishlist - missing productId field
  # Verify 400 when required productId field is missing
  Given path '/wishlist'
  And header token = authToken
  And request {}
  When method POST
  Then status 400

Scenario: Add product to wishlist - invalid productId data type
  # Verify 400 when productId is not a string
  Given path '/wishlist'
  And header token = authToken
  And request { "productId": 12345 }
  When method POST
  Then status 400

Scenario: Add product to wishlist - with non-existent product ID
  # Verify 400 when product ID doesn't exist in system
  Given path '/wishlist'
  And header token = authToken
  And request { "productId": "000000000000000000000000" }
  When method POST
  Then status 400

Scenario: Add product to wishlist - with invalid ObjectId format
  # Verify 500 when productId format is invalid
  Given path '/wishlist'
  And header token = authToken
  And request { "productId": "invalid-id" }
  When method POST
  Then status 500

Scenario: Remove product from wishlist - happy path
  # First add product to wishlist, then remove it
  Given path '/wishlist'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  # Now remove it
  Given path '/wishlist/' + productId
  And header token = authToken
  When method DELETE
  Then status 200

Scenario: Remove product from wishlist - without authentication token
  # Verify 401 when removing from wishlist without token
  Given path '/wishlist/' + productId
  When method DELETE
  Then status 401

Scenario: Remove product from wishlist - with invalid token
  # Verify 401 when removing from wishlist with malformed token
  Given path '/wishlist/' + productId
  And header token = 'invalid-token'
  When method DELETE
  Then status 401

Scenario: Remove product from wishlist - product not in wishlist
  # Verify 404 when trying to remove product that is not in wishlist
  Given path '/wishlist/000000000000000000000000'
  And header token = authToken
  When method DELETE
  Then status 404

Scenario: Remove product from wishlist - invalid ObjectId format
  # Verify 500 when productId format is invalid
  Given path '/wishlist/invalid-id'
  And header token = authToken
  When method DELETE
  Then status 500

Scenario: Add multiple products to wishlist and verify they all appear
  # Verify user can add multiple products and retrieve complete wishlist
  Given path '/wishlist'
  And header token = authToken
  And request { "productId": "#(productId)" }
  When method POST
  Then status 200
  # Get wishlist and verify product is present
  Given path '/wishlist'
  And header token = authToken
  When method GET
  Then status 200
  And match response.data[0]._id == productId